# Generated by Django 2.2.24 on 2021-12-10 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialingReqest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A UUID assigned to a prod credentialing request', primary_key=True, serialize=False, unique=True, verbose_name='Prod Credentialing Request ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('visits_count', models.IntegerField(default=0)),
                ('application', models.ForeignKey(help_text='Target application of a prod credentialing request', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Application')),
            ],
        ),
    ]
