# Generated by Django 4.2.26 on 2025-12-16 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.BigIntegerField()),
                ('event_hash', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_tag', models.TextField()),
                ('metric_description', models.TextField()),
                ('metric_value', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.BigIntegerField()),
                ('event_hash', models.BigIntegerField()),
                ('source_name', models.TextField()),
                ('event_name', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'unique_together': {('source_hash', 'event_hash')},
            },
        ),
    ]
