import re
from apps.constants import LAUNCH_SCOPE, OPENID_SCOPE

# REGEX of paths that should be updated with auth flow info in hhs_oauth_server.request_logging.py
AUTH_FLOW_REQUEST_LOGGING_PATHS_REGEX = (
    '(^/v[1|2|3]/o/authorize/.*|^/mymedicare/login$|^/mymedicare/sls-callback$|^/v[1|2|3]/o/token/$)'
)

AUTHORIZE_INSTANCE_PARAM = 'uuid'

DELETE_WITH_LIMIT = """DELETE FROM {table_name} WHERE auth_uuid IN
(SELECT auth_uuid FROM {table_name} WHERE created < '{age_date}'::date ORDER BY created LIMIT {limit_on_delete})"""

HEADERS = {
    'Remaining': 'X-RateLimit-Remaining',
    'Limit': 'X-RateLimit-Limit',
    'Reset': 'X-RateLimit-Reset',
}
PRINTABLE_SPECIAL_ASCII = '!"#$%&\'()*+,-/:;<=>?@[\\]^_`{|}~'

# List of value keys that are being tracked via request.session
SESSION_AUTH_FLOW_TRACE_KEYS = [
    'auth_uuid',
    'auth_client_id',
    'auth_grant_type',
    'auth_app_id',
    'auth_app_name',
    'auth_app_data_access_type',
    'auth_pkce_method',
    'auth_crosswalk_action',
    'auth_share_demographic_scopes',
    'auth_require_demographic_scopes',
    'auth_language',
]

SUPPORTED_VERSION_TEST_CASES = [
    {'url_path': '/v2/fhir/Patient/', 'expected': 2},
    # return 0 because v2 does not have a leading /
    {'url_path': 'v2/fhir/Patient/', 'expected': 0},
    {'url_path': '/v3/fhir/Coverage/', 'expected': 3},
    {'url_path': '/v3/fhir/Coverage/v2/', 'expected': 3},
]

TARGET_TABLE_COPY = 'dot_ext_authflowuuidcopy'
TARGET_TABLE = 'dot_ext_authflowuuid'

TOKEN_ENDPOINT_V1_KEY = 'token'
TOKEN_ENDPOINT_V2_KEY = 'token-v2'
TOKEN_ENDPOINT_V3_KEY = 'token-v3'

URL_REGEX = re.compile(
    r'^(https:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.'
    r'[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$'
)

"""
    Test Cases for demographic scopes related testing
    Dictionaries included:
        FORM_OAUTH2_SCOPES_TEST_CASES - For testing OAUTH2 form cleaned data
        VIEW_OAUTH2_SCOPES_TEST_CASES - For testing OAUTH2 authorization views
"""
# Scopes lists for testing
#   Note that additional scopes, like capability-a/b (not actually used for BB2), are included
#   to test that the limiting of the resource related endpoints don't affect them.
APPLICATION_SCOPES_FULL = [
    'patient/Patient.read',
    'profile',
    'patient/ExplanationOfBenefit.read',
    'patient/Coverage.read',
    'capability-a',
    'capability-b',
]
APPLICATION_SCOPES_NON_DEMOGRAPHIC = [
    'patient/ExplanationOfBenefit.read',
    'patient/Coverage.read',
    'capability-a',
    'capability-b',
]

# Various scopes used to test requested and assigned/granted to access tokens
SCOPES_JUST_PATIENT = ['patient/Patient.read']
SCOPES_JUST_PATIENT_AND_A = ['patient/Patient.read', 'capability-a']
SCOPES_JUST_A = ['capability-a']
SCOPES_JUST_EOB_AND_B = ['patient/ExplanationOfBenefit.read', 'capability-b']
SCOPES_JUST_EMPTY = []
V2_SCOPES_ALL = [
    'patient/Patient.r',
    'patient/Patient.s',
    'patient/Patient.rs',
    'patient/ExplanationOfBenefit.r',
    'patient/ExplanationOfBenefit.s',
    'patient/ExplanationOfBenefit.rs',
    'patient/Coverage.r',
    'patient/Coverage.s',
    'patient/Coverage.rs',
    LAUNCH_SCOPE,
    OPENID_SCOPE,
]
V2_SCOPES_ALL_CONDENSED = [
    'patient/Patient.rs',
    'patient/ExplanationOfBenefit.rs',
    'patient/Coverage.rs',
    LAUNCH_SCOPE,
    OPENID_SCOPE,
]
V2_SCOPES_NON_DEMOGRAPHIC = [
    'patient/ExplanationOfBenefit.r',
    'patient/ExplanationOfBenefit.s',
    'patient/ExplanationOfBenefit.rs',
    'patient/Coverage.r',
    'patient/Coverage.s',
    'patient/Coverage.rs',
    LAUNCH_SCOPE,
    OPENID_SCOPE,
]
V2_SCOPES_NON_DEMOGRAPHIC_CONDENSED = ['patient/ExplanationOfBenefit.rs', 'patient/Coverage.rs', LAUNCH_SCOPE, OPENID_SCOPE]

# Scope to base URL PATH mapping.
SCOPES_TO_URL_BASE_PATH = {
    'profile': {
        'base_path': '/v1/connect/userinfo',
        'is_fhir_url': False,
    },
    'patient/Patient.read': {
        'base_path': '/v1/fhir/Patient',
        'is_fhir_url': True,
        # The ReadView should be tested.
        'test_readview': True,
    },
    'patient/ExplanationOfBenefit.read': {
        'base_path': '/v1/fhir/ExplanationOfBenefit',
        'is_fhir_url': True,
    },
    'patient/Coverage.read': {
        'base_path': '/v1/fhir/Coverage',
        'is_fhir_url': True,
    },
}

"""
    FORM_OAUTH2_SCOPES_TEST_CASES test case dictionary
    --------------------------------------------------
    USED in the following test:
      apps.dot_ext.tests.test_form_oauth2
                        .TestSimpleAllowForm.test_form()
    Test case dictionary key and value meanings:
    REQUEST PARAMETERS:
      These are used to setup the authorization request.
      - request_bene_share_demographic_scopes = [None, True, False]
            Did the beneficiary choose to share demographic info?
      - request_scopes = The scopes being requested in the authorization request.
    EXPECTED RESULTS:
      These are used to validate the authorization request results.
      - result_form_is_valid = [True, False]
            What is the expected result for form.is_valid()?
      - result_token_scopes_granted = The List of scopes expected
            to be assigned to the resulting access token.
"""
FORM_OAUTH2_SCOPES_TEST_CASES = {
    'test 1: share_demographic_scopes = None': {
        # Request:
        'request_bene_share_demographic_scopes': None,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
    },
    'test 2: share_demographic_scopes = False': {
        # Request:
        'request_bene_share_demographic_scopes': False,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
    },
    'test 3: share_demographic_scopes = True': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': APPLICATION_SCOPES_FULL,
    },
    'test 4: share = True request just EOB and B': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_EOB_AND_B,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_EOB_AND_B,
    },
    'test 5: share = True request just PATIENT and A': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_PATIENT_AND_A,
    },
    'test 6: share = False request just EOB and B': {
        # Request:
        'request_bene_share_demographic_scopes': False,
        'request_scopes': SCOPES_JUST_EOB_AND_B,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_EOB_AND_B,
    },
    'test 7: share = False request just PATIENT and A': {
        # Request:
        'request_bene_share_demographic_scopes': False,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_A,
    },
    'test 8: share = True request just PATIENT': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_PATIENT,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_PATIENT,
    },
    'test 9: share = False request just PATIENT': {
        # Request:
        'request_bene_share_demographic_scopes': False,
        'request_scopes': SCOPES_JUST_PATIENT,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': SCOPES_JUST_EMPTY,
    },
    'test 10: share = True request just EMPTY': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_EMPTY,
        # Result:
        'result_form_is_valid': False,
        'result_token_scopes_granted': SCOPES_JUST_EMPTY,
    },
    'test 11: share = True v2 Scopes': {
        # Request:
        'request_bene_share_demographic_scopes': True,
        'request_scopes': V2_SCOPES_ALL,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': V2_SCOPES_ALL_CONDENSED,
    },
    'test 11: share = False v2 Scopes': {
        # Request:
        'request_bene_share_demographic_scopes': False,
        'request_scopes': V2_SCOPES_ALL,
        # Result:
        'result_form_is_valid': True,
        'result_token_scopes_granted': V2_SCOPES_NON_DEMOGRAPHIC_CONDENSED,
    },
}

"""
    VIEW_OAUTH2_SCOPES_TEST_CASES test case dictionary
    --------------------------------------------------
    USED in the following test:
      apps.dot_ext.tests.test_views
                        .TestAuthorizationView.test_post_with_post_with_demographic_scope_choices()
    Test case dictionary key and value meanings:
    REQUEST PARAMETERS:
      These are used to setup the authorization request.
      - request_bene_share_demographic_scopes = [None, True, False]
            Does the beneficiary choose to share demographic info?
      - request_app_requires_demographic = [None, True, False]
            Does the application choose to require demographic info?
      - request_scopes = The scopes being requested in the authorization request.
    EXPECTED RESULTS:
      These are used to validate the authorization request results.
      - result_has_error = [True, False]
            Is an error in the result expected?
      - result_token_scopes_granted = The List of scopes expected
            to be assigned to the resulting access token.
      - result_raises_exception = The exception raised.
      - result_exception_mesg =  Exception message REGEX.
      Expected count after token granted and related to token/grant cleanups:
      - result_access_token_count = Expected count.
      - result_refresh_token_count = Expected count.
      - result_archived_token_count = Expected count.
      - result_archived_data_access_grant_count = Expected count.
"""
VIEW_OAUTH2_SCOPES_TEST_CASES = {
    # Tests for app_require_demographic_scopes = None
    'test 1: app_requires = None bene_share = None': {
        # Request:
        'request_app_requires_demographic': None,
        'request_bene_share_demographic_scopes': None,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 0,
        'result_archived_data_access_grant_count': 0,
    },
    'test 2: app_requires = None bene_share = False': {
        # Request:
        'request_app_requires_demographic': None,
        'request_bene_share_demographic_scopes': False,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 1,
        'result_archived_data_access_grant_count': 1,
    },
    'test 3: app_requires = None bene_share = True': {
        # Request:
        'request_app_requires_demographic': None,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_FULL,
        'result_access_token_count': 2,
        'result_refresh_token_count': 2,
        'result_archived_token_count': 1,
        'result_archived_data_access_grant_count': 1,
    },
    # Tests for request_app_requires_demographic = True
    'test 4: app_requires = True bene_share = None': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': None,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 3,
        'result_refresh_token_count': 3,
        'result_archived_token_count': 1,
        'result_archived_data_access_grant_count': 1,
    },
    'test 5: app_requires = True bene_share = False': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': False,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 4,
        'result_archived_data_access_grant_count': 2,
    },
    'test 6: app_requires = True bene_share = True': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_FULL,
        'result_access_token_count': 2,
        'result_refresh_token_count': 2,
        'result_archived_token_count': 4,
        'result_archived_data_access_grant_count': 2,
    },
    # Tests for request_app_requires_demographic = False
    'test 7: app_requires = False bene_share = None': {
        # Request:
        'request_app_requires_demographic': False,
        'request_bene_share_demographic_scopes': None,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 6,
        'result_archived_data_access_grant_count': 3,
    },
    'test 8: app_requires = False bene_share = False': {
        # Request:
        'request_app_requires_demographic': False,
        'request_bene_share_demographic_scopes': False,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 7,
        'result_archived_data_access_grant_count': 4,
    },
    'test 9: app_requires = False bene_share = True': {
        # Request:
        'request_app_requires_demographic': False,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': APPLICATION_SCOPES_FULL,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': APPLICATION_SCOPES_NON_DEMOGRAPHIC,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 8,
        'result_archived_data_access_grant_count': 5,
    },
    # Misc tests where only partial scopes are requested for authorization
    'test 10: app_requires = True bene_share = True request just EOB and B': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_EOB_AND_B,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_EOB_AND_B,
        'result_access_token_count': 2,
        'result_refresh_token_count': 2,
        'result_archived_token_count': 8,
        'result_archived_data_access_grant_count': 5,
    },
    'test 11: app_requires = None bene_share = None request just PATIENT and A': {
        # Request:
        'request_app_requires_demographic': None,
        'request_bene_share_demographic_scopes': None,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_A,
        'result_access_token_count': 3,
        'result_refresh_token_count': 3,
        'result_archived_token_count': 8,
        'result_archived_data_access_grant_count': 5,
    },
    'test 12: app_requires = True bene_share = True request just PATIENT and A': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_PATIENT_AND_A,
        'result_access_token_count': 4,
        'result_refresh_token_count': 4,
        'result_archived_token_count': 8,
        'result_archived_data_access_grant_count': 5,
    },
    'test 13: app_requires = False bene_share = True request just PATIENT and A': {
        # Request:
        'request_app_requires_demographic': False,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_A,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 12,
        'result_archived_data_access_grant_count': 6,
    },
    'test 14: app_requires = True bene_share = False request just PATIENT and A': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': False,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_A,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 13,
        'result_archived_data_access_grant_count': 7,
    },
    'test 15: app_requires = None bene_share = False request just PATIENT and A': {
        # Request:
        'request_app_requires_demographic': None,
        'request_bene_share_demographic_scopes': False,
        'request_scopes': SCOPES_JUST_PATIENT_AND_A,
        # Result:
        'result_has_error': False,
        'result_token_scopes_granted': SCOPES_JUST_A,
        'result_access_token_count': 1,
        'result_refresh_token_count': 1,
        'result_archived_token_count': 14,
        'result_archived_data_access_grant_count': 8,
    },
    # Testing initial auth request has request_scopes = None
    #   The POST to oauth2_provider:authorize must have scope in the payload.
    'test 16: app_requires = True bene_share = True request scopes = None': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': None,
        # Result:  NOTE: This case has empty scopes on POST!
        'result_has_error': True,
        'result_raises_exception': AssertionError,
    },
    # Testing case that produce ValueError exception
    # Test case 17, 18 assertion no longer holds
    #
    # BB2-1224 Django upgrade to 3.2.13, this is no longer the case with oauthlib 3.1.0:
    # oauthlib/oauth2/rfc6749/grant_types/authorization_code.py->create_authorization_response(...)
    # no longer check scopes is None and throw ValueError as shown below (oauthlib 2.1.0):
    # if not request.scopes:
    #    raise ValueError('Scopes must be set on post auth.')
    # "test 17: app_requires = False bene_share = True request just PATIENT error=True": {
    #     # Request:
    #     "request_app_requires_demographic": False,
    #     "request_bene_share_demographic_scopes": True,
    #     "request_scopes": SCOPES_JUST_PATIENT,
    #     # Result:  NOTE: Since Patient is not allowed,
    #     #                this case results in having empty scopes on post auth!
    #     "result_has_error": True,
    #     "result_raises_exception": ValueError,
    #     "result_exception_mesg": "Scopes must be set on post auth.",
    # },
    # Testing case that produce ValueError exception
    # "test 18: app_requires = True bene_share = False request just PATIENT error=True": {
    #     # Request:
    #     "request_app_requires_demographic": True,
    #     "request_bene_share_demographic_scopes": False,
    #     "request_scopes": SCOPES_JUST_PATIENT,
    #     # Result:  NOTE: Since Patient is not allowed,
    #     #                this case results in having empty scopes on post auth!
    #     "result_has_error": True,
    #     "result_raises_exception": ValueError,
    #     "result_exception_mesg": "Scopes must be set on post auth.",
    # },
    # Testing cases that produces AssertionError in _authorize_and_request_token()
    'test 19: app_requires = True bene_share = True request just empty scopes error=True': {
        # Request:
        'request_app_requires_demographic': True,
        'request_bene_share_demographic_scopes': True,
        'request_scopes': SCOPES_JUST_EMPTY,
        # Result:  NOTE: This case has an empty List in POST request payload!
        'result_has_error': True,
        'result_raises_exception': AssertionError,
        'result_exception_mesg': '200 != 302',
    },
}

# List of beneficiary personal information resource type scopes
BENE_PERSONAL_INFO_SCOPES = [
    'patient/Patient.read',
    'patient/Patient.s',
    'patient/Patient.r',
    'patient/Patient.rs',
    'profile',
]

APPLICATION_THIRTEEN_MONTH_DATA_ACCESS_NOT_FOUND_MESG = (
    'User access cannot be found. To refresh Medicare data, end user must re-authenticate and consent to share their data.'
)

APPLICATION_DOES_NOT_HAVE_CLIENT_CREDENTIALS_ENABLED = (
    'This application, {}, does not yet have access to this authorization method.'
    ' If you are the app maintainer, please contact the Blue Button API team.'
    ' If you are a Medicare Beneficiary and need assistance, please contact'
    ' the support team for the application you are trying to access.'
)

CSP_IAL_ACCEPTED_JWT_ALGORITHMS = ['RS256']
CLIENT_ASSERTION_TYPE_VALUE = 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer'

# TODO - use env vars to determine which enviornment is valid, at the moment all of them are
CLEAR_HIGHER_JWKS_URL = 'https://verified.clearme.com/integrations/.well-known/jwks.json'
CLEAR_LOWER_JWKS_URL = 'https://please-find-out-what-i.am'
IDME_HIGHER_JWKS_URL = 'https://api.id.me/oidc/.well-known/jwks'
IDME_LOWER_JWKS_URL = 'https://api.idmelabs.com/oidc/.well-known/jwks'


CLEAR_HIGHER_ISS = 'https://verified.clearme.com/integrations'
CLEAR_LOWER_ISS = 'https://please-find-out-what-i.am'
IDME_HIGHER_ISS = 'https://api.id.me/oidc'
IDME_LOWER_ISS = 'https://api.idmelabs.com/oidc'

JWKS_URLS = {
    CLEAR_HIGHER_ISS: CLEAR_HIGHER_JWKS_URL,
    CLEAR_LOWER_ISS: CLEAR_LOWER_JWKS_URL,
    IDME_HIGHER_ISS: IDME_HIGHER_JWKS_URL,
    IDME_LOWER_ISS: IDME_LOWER_JWKS_URL,
}

FHIR_ROOT_OID = 'urn:oid:2.16.840.1.113883'
APPLICATION_HAS_CLIENT_CREDENTIALS_ENABLED_NON_CLIENT_CREDENTIALS_AUTH_CALL_MADE = (
    'This authorization call type is not allowed for application, {}.'
    ' If you are the app maintainer, please contact the Blue Button API team.'
    ' If you are a Medicare Beneficiary and need assistance, please contact'
    ' the support team for the application you are trying to access.'
)

AUTH_CODE_TYPE = 'AUTH_CODE'
CLIENT_CREDENTIALS_TYPE = 'CLIENT_CREDENTIALS'
AUTH_CODE_AND_CLIENT_CREDENTIALS_TYPE = 'AUTH_CODE_AND_CLIENT_CREDS'

CLIENT_CREDENTIALS_SUPPORTED_TYPES = [CLIENT_CREDENTIALS_TYPE, AUTH_CODE_AND_CLIENT_CREDENTIALS_TYPE]
AUTH_CODE_SUPPORTED_TYPES = [AUTH_CODE_TYPE, AUTH_CODE_AND_CLIENT_CREDENTIALS_TYPE]

YYYY_MM_DD_REGEX = r'^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$'

CC_SYSTEM_CODING_SYSTEM = 'http://terminology.hl7.org/CodeSystem/v2-0203'
CC_SYSTEM_SOCIAL_SECURITY_NUMBER = 'http://hl7.org/fhir/sid/us-ssn'
CC_SYSTEM_MEDICARE_NUMBER = 'http://hl7.org/fhir/sid/us-mbi'

PARAMETERS_ID_MATCH_META = 'http://hl7.org/fhir/us/identity-matching/StructureDefinition/idi-match-input-parameters'
PATIENT_ID_MATCH_META = 'http://hl7.org/fhir/us/identity-matching/StructureDefinition/IDI-Patient'

STATES = {
    'ALABAMA': 'AL',
    'ALASKA': 'AK',
    'AMERICAN SAMOA': 'AS',
    'ARIZONA': 'AZ',
    'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA',
    'COLORADO': 'CO',
    'CONNECTICUT': 'CT',
    'DELAWARE': 'DE',
    'DISTRICT OF COLUMBIA': 'DC',
    'FEDERATED STATES OF MICRONESIA': 'FM',
    'FLORIDA': 'FL',
    'GEORGIA': 'GA',
    'GUAM': 'GU',
    'HAWAII': 'HI',
    'IDAHO': 'ID',
    'ILLINOIS': 'IL',
    'INDIANA': 'IN',
    'IOWA': 'IA',
    'KANSAS': 'KS',
    'KENTUCKY': 'KY',
    'LOUISIANA': 'LA',
    'MAINE': 'ME',
    'MARSHALL ISLANDS': 'MH',
    'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA',
    'MICHIGAN': 'MI',
    'MINNESOTA': 'MN',
    'MISSISSIPPI': 'MS',
    'MISSOURI': 'MO',
    'MONTANA': 'MT',
    'NEBRASKA': 'NE',
    'NEVADA': 'NV',
    'NEW HAMPSHIRE': 'NH',
    'NEW JERSEY': 'NJ',
    'NEW MEXICO': 'NM',
    'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC',
    'NORTH DAKOTA': 'ND',
    'NORTHERN MARIANA ISLANDS': 'MP',
    'OHIO': 'OH',
    'OKLAHOMA': 'OK',
    'OREGON': 'OR',
    'PALAU': 'PW',
    'PENNSYLVANIA': 'PA',
    'PUERTO RICO': 'PR',
    'RHODE ISLAND': 'RI',
    'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD',
    'TENNESSEE': 'TN',
    'TEXAS': 'TX',
    'UTAH': 'UT',
    'VERMONT': 'VT',
    'VIRGIN ISLANDS': 'VI',
    'VIRGINIA': 'VA',
    'WASHINGTON': 'WA',
    'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI',
    'WYOMING': 'WY',
}

SECONDARY_UNITS = {
    'APARTMENT': 'APT',
    'BASEMENT': 'BSMT',
    'BUILDING': 'BLDG',
    'DEPARTMENT': 'DEPT',
    'FLOOR': 'FL',
    'FRONT': 'FRNT',
    'HANGER': 'HNGR',
    'KEY': 'KEY',
    'LOBBY': 'LBBY',
    'LOT': 'LOT',
    'LOWER': 'LOWR',
    'OFFICE': 'OFC',
    'PENTHOUSE': 'PH',
    'PIER': 'PIER',
    'REAR': 'REAR',
    'ROOM': 'RM',
    'SIDE': 'SIDE',
    'SLIP': 'SLIP',
    'SPACE': 'SPC',
    'STOP': 'STOP',
    'SUITE': 'STE',
    'TRAILER': 'TRLR',
    'UNIT': 'UNIT',
    'UPPER': 'UPPR',
}

# Mapping of common suffixes to standard USPS/Project US@ abbreviations.
# This list is comprehensive to handle standard conversions.
SUFFIX_MAP = {
    'ALLEY': 'ALY',
    'ALLEE': 'ALY',
    'ALLY': 'ALY',
    'ANEX': 'ANX',
    'ANNEX': 'ANX',
    'ANNX': 'ANX',
    'ARCADE': 'ARC',
    'AVENUE': 'AVE',
    'AVEN': 'AVE',
    'AVENU': 'AVE',
    'AVN': 'AVE',
    'AVNUE': 'AVE',
    'BAYOU': 'BYU',
    'BAYOO': 'BYU',
    'BEACH': 'BCH',
    'BEND': 'BND',
    'BLUFF': 'BLF',
    'BLUF': 'BLF',
    'BLUFFS': 'BLFS',
    'BOTTOM': 'BTM',
    'BOT': 'BTM',
    'BOTTM': 'BTM',
    'BOULEVARD': 'BLVD',
    'BOUL': 'BLVD',
    'BOULV': 'BLVD',
    'BRANCH': 'BR',
    'BRNCH': 'BR',
    'BRIDGE': 'BRG',
    'BRDGE': 'BRG',
    'BROOK': 'BRK',
    'BROOKS': 'BRKS',
    'BURG': 'BG',
    'BURGS': 'BGS',
    'BYPASS': 'BYP',
    'BYPA': 'BYP',
    'BYPAS': 'BYP',
    'BYPS': 'BYP',
    'CAMP': 'CP',
    'CMP': 'CP',
    'CANYON': 'CYN',
    'CANYN': 'CYN',
    'CNYN': 'CYN',
    'CAPE': 'CPE',
    'CAUSEWAY': 'CSWY',
    'CAUSWA': 'CSWY',
    'CENTER': 'CTR',
    'CEN': 'CTR',
    'CENT': 'CTR',
    'CENTR': 'CTR',
    'CENTRE': 'CTR',
    'CNTER': 'CTR',
    'CNTR': 'CTR',
    'CENTERS': 'CTRS',
    'CIRCLE': 'CIR',
    'CIRC': 'CIR',
    'CIRCL': 'CIR',
    'CRCL': 'CIR',
    'CRCLE': 'CIR',
    'CIRCLES': 'CIRS',
    'CLIFF': 'CLF',
    'CLIFFS': 'CLFS',
    'CLUB': 'CLB',
    'COMMON': 'CMN',
    'COMMONS': 'CMNS',
    'CORNER': 'COR',
    'CORNERS': 'CORS',
    'COURSE': 'CRSE',
    'COURT': 'CT',
    'COURTS': 'CTS',
    'COVE': 'CV',
    'COVES': 'CVS',
    'CREEK': 'CRK',
    'CRESCENT': 'CRES',
    'CRSENT': 'CRES',
    'CRSNT': 'CRES',
    'CREST': 'CRST',
    'CROSSING': 'XING',
    'CRSSNG': 'XING',
    'CROSSROAD': 'XRD',
    'CROSSROADS': 'XRDS',
    'CURVE': 'CURV',
    'DALE': 'DL',
    'DAM': 'DM',
    'DIVIDE': 'DV',
    'DIV': 'DV',
    'DVD': 'DV',
    'DRIVE': 'DR',
    'DRIV': 'DR',
    'DRV': 'DR',
    'DRIVES': 'DRS',
    'ESTATE': 'EST',
    'ESTATES': 'ESTS',
    'EXPRESSWAY': 'EXPY',
    'EXP': 'EXPY',
    'EXPR': 'EXPY',
    'EXPRESS': 'EXPY',
    'EXPW': 'EXPY',
    'EXTENSION': 'EXT',
    'EXTN': 'EXT',
    'EXTNSN': 'EXT',
    'EXTENSIONS': 'EXTS',
    'FALL': 'FALL',
    'FALLS': 'FLS',
    'FERRY': 'FRY',
    'FRRY': 'FRY',
    'FIELD': 'FLD',
    'FIELDS': 'FLDS',
    'FLAT': 'FLT',
    'FLATS': 'FLTS',
    'FORD': 'FRD',
    'FORDS': 'FRDS',
    'FOREST': 'FRST',
    'FORESTS': 'FRST',
    'FORGE': 'FRG',
    'FORG': 'FRG',
    'FORGES': 'FRGS',
    'FORK': 'FRK',
    'FORKS': 'FRKS',
    'FORT': 'FT',
    'FRT': 'FT',
    'FREEWAY': 'FWY',
    'FREEWY': 'FWY',
    'FRWAY': 'FWY',
    'FRWY': 'FWY',
    'GARDEN': 'GDN',
    'GARDN': 'GDN',
    'GRDEN': 'GDN',
    'GRDN': 'GDN',
    'GARDENS': 'GDNS',
    'GRDNS': 'GDNS',
    'GATEWAY': 'GTWY',
    'GATEWY': 'GTWY',
    'GATWAY': 'GTWY',
    'GTWAY': 'GTWY',
    'GLEN': 'GLN',
    'GLENS': 'GLNS',
    'GREEN': 'GRN',
    'GREENS': 'GRNS',
    'GROVE': 'GRV',
    'GROV': 'GRV',
    'GROVES': 'GRVS',
    'HARBOR': 'HBR',
    'HARB': 'HBR',
    'HARBR': 'HBR',
    'HRBOR': 'HBR',
    'HARBORS': 'HBRS',
    'HAVEN': 'HVN',
    'HEIGHTS': 'HTS',
    'HT': 'HTS',
    'HIGHWAY': 'HWY',
    'HIGHWY': 'HWY',
    'HIWAY': 'HWY',
    'HIWY': 'HWY',
    'HWAY': 'HWY',
    'HILL': 'HL',
    'HILLS': 'HLS',
    'HOLLOW': 'HOLW',
    'HLLW': 'HOLW',
    'HOLLOWS': 'HOLW',
    'HOLWS': 'HOLW',
    'INLET': 'INLT',
    'ISLAND': 'IS',
    'ISLND': 'IS',
    'ISLANDS': 'ISS',
    'ISLNDS': 'ISS',
    'ISLE': 'ISLE',
    'ISLES': 'ISLE',
    'JUNCTION': 'JCT',
    'JCTION': 'JCT',
    'JCTN': 'JCT',
    'JUNCTN': 'JCT',
    'JUNCTON': 'JCT',
    'JUNCTIONS': 'JCTS',
    'JCTNS': 'JCTS',
    'KEY': 'KY',
    'KEYS': 'KYS',
    'KNOLL': 'KNL',
    'KNOL': 'KNL',
    'KNOLLS': 'KNLS',
    'LAKE': 'LK',
    'LAKES': 'LKS',
    'LAND': 'LAND',
    'LANDING': 'LNDG',
    'LNDNG': 'LNDG',
    'LANE': 'LN',
    'LIGHT': 'LGT',
    'LIGHTS': 'LGTS',
    'LOAF': 'LF',
    'LOCK': 'LCK',
    'LOCKS': 'LCKS',
    'LODGE': 'LDG',
    'LDGE': 'LDG',
    'LODG': 'LDG',
    'LOOP': 'LOOP',
    'LOOPS': 'LOOP',
    'MALL': 'MALL',
    'MANOR': 'MNR',
    'MANORS': 'MNRS',
    'MEADOW': 'MDW',
    'MEADOWS': 'MDWS',
    'MEDOWS': 'MDWS',
    'MEWS': 'MEWS',
    'MILL': 'ML',
    'MILLS': 'MLS',
    'MISSION': 'MSN',
    'MISSN': 'MSN',
    'MSSN': 'MSN',
    'MOTORWAY': 'MTWY',
    'MOUNT': 'MT',
    'MNT': 'MT',
    'MOUNTAIN': 'MTN',
    'MNTAIN': 'MTN',
    'MNTN': 'MTN',
    'MOUNTIN': 'MTN',
    'MTIN': 'MTN',
    'MOUNTAINS': 'MTNS',
    'MNTNS': 'MTNS',
    'NECK': 'NCK',
    'ORCHARD': 'ORCH',
    'ORCHRD': 'ORCH',
    'OVAL': 'OVAL',
    'OVL': 'OVAL',
    'OVERPASS': 'OPAS',
    'PARK': 'PARK',
    'PRK': 'PARK',
    'PARKS': 'PARK',  # the pdf has PARKS -> PARK
    'PARKWAY': 'PKWY',
    'PARKWY': 'PKWY',
    'PKWAY': 'PKWY',
    'PKY': 'PKWY',
    'PARKWAYS': 'PKWY',
    'PKWYS': 'PKWY',
    'PASS': 'PASS',
    'PASSAGE': 'PSGE',
    'PATH': 'PATH',
    'PATHS': 'PATH',
    'PIKE': 'PIKE',
    'PIKES': 'PIKE',
    'PINE': 'PNE',
    'PINES': 'PNES',
    'PLACE': 'PL',
    'PLAIN': 'PLN',
    'PLAINS': 'PLNS',
    'PLAZA': 'PLZ',
    'PLZA': 'PLZ',
    'POINT': 'PT',
    'POINTS': 'PTS',
    'PORT': 'PRT',
    'PORTS': 'PRTS',
    'PRAIRIE': 'PR',
    'PRR': 'PR',
    'RADIAL': 'RADL',
    'RAD': 'RADL',
    'RADIEL': 'RADL',
    'RAMP': 'RAMP',
    'RANCH': 'RNCH',
    'RANCHES': 'RNCH',
    'RNCHS': 'RNCH',
    'RAPID': 'RPD',
    'RAPIDS': 'RPDS',
    'REST': 'RST',
    'RIDGE': 'RDG',
    'RDGE': 'RDG',
    'RIDGES': 'RDGS',
    'RIVER': 'RIV',
    'RVR': 'RIV',
    'RIVR': 'RIV',
    'ROAD': 'RD',
    'ROADS': 'RDS',
    'ROUTE': 'RTE',
    'ROW': 'ROW',
    'RUE': 'RUE',
    'RUN': 'RUN',
    'SHOAL': 'SHL',
    'SHOALS': 'SHLS',
    'SHORE': 'SHR',
    'SHOAR': 'SHR',
    'SHORES': 'SHRS',
    'SHOARS': 'SHRS',
    'SKYWAY': 'SKWY',
    'SPRING': 'SPG',
    'SPNG': 'SPG',
    'SPRNG': 'SPG',
    'SPRINGS': 'SPGS',
    'SPNGS': 'SPGS',
    'SPRNGS': 'SPGS',
    'SPUR': 'SPUR',
    'SPURS': 'SPUR',
    'SQUARE': 'SQ',
    'SQR': 'SQ',
    'SQRE': 'SQ',
    'SQU': 'SQ',
    'SQUARES': 'SQS',
    'SQRS': 'SQS',
    'STATION': 'STA',
    'STATN': 'STA',
    'STN': 'STA',
    'STRAVENUE': 'STRA',
    'STRAV': 'STRA',
    'STRAVEN': 'STRA',
    'STRAVN': 'STRA',
    'STRVN': 'STRA',
    'STRVNUE': 'STRA',
    'STREAM': 'STRM',
    'STREME': 'STRM',
    'STREET': 'ST',
    'STRT': 'ST',
    'STR': 'ST',
    'STREETS': 'STS',
    'SUMMIT': 'SMT',
    'SUMIT': 'SMT',
    'SUMITT': 'SMT',
    'TERRACE': 'TER',
    'TERR': 'TER',
    'THROUGHWAY': 'TRWY',
    'TRACE': 'TRCE',
    'TRACES': 'TRCE',
    'TRACK': 'TRAK',
    'TRACKS': 'TRAK',
    'TRK': 'TRAK',
    'TRKS': 'TRAK',
    'TRAFFICWAY': 'TRFY',
    'TRAIL': 'TRL',
    'TRAILS': 'TRL',
    'TRLS': 'TRL',
    'TRAILER': 'TRLR',
    'TRLRS': 'TRLR',
    'TUNNEL': 'TUNL',
    'TUNEL': 'TUNL',
    'TUNLS': 'TUNL',
    'TUNNELS': 'TUNL',
    'TUNNL': 'TUNL',
    'TURNPIKE': 'TPKE',
    'TRNPK': 'TPKE',
    'TURNPK': 'TPKE',
    'UNDERPASS': 'UPAS',
    'UNION': 'UN',
    'UNIONS': 'UNS',
    'VALLEY': 'VLY',
    'VALLY': 'VLY',
    'VLLY': 'VLY',
    'VALLEYS': 'VLYS',
    'VIADUCT': 'VIA',
    'VDCT': 'VIA',
    'VIADCT': 'VIA',
    'VIEW': 'VW',
    'VIEWS': 'VWS',
    'VILLAGE': 'VLG',
    'VILL': 'VLG',
    'VILLAG': 'VLG',
    'VILLG': 'VLG',
    'VILLIAGE': 'VLG',
    'VILLAGES': 'VLGS',
    'VILLE': 'VL',
    'VISTA': 'VIS',
    'VIST': 'VIS',
    'VST': 'VIS',
    'VSTA': 'VIS',
    'WALK': 'WALK',
    'WALKS': 'WALK',
    'WALL': 'WALL',
    'WAY': 'WAY',
    'WY': 'WAY',
    'WAYS': 'WAYS',
    'WELL': 'WL',
    'WELLS': 'WLS',
}

DIRECTIONALS = {
    'NORTH': 'N',
    'SOUTH': 'S',
    'EAST': 'E',
    'WEST': 'W',
    'NORTHEAST': 'NE',
    'NORTHWEST': 'NW',
    'SOUTHEAST': 'SE',
    'SOUTHWEST': 'SW',
}

PR_URBANIZATION_EXCEPTIONS = {
    'ALTURA': 'ALT',
    'ALTURAS': 'ALTS',
    'BARRIADA': 'BDA',
    'BARRIO': 'BO',
    'BOSQUE': 'BOSQUE',
    'BRISA': 'BRISA',
    'BRISAS': 'BRISAS',
    'CIUDAD': 'CIUDAD',
    'COLINA': 'COLINA',
    'COLINAS': 'COLINAS',
    'CHALETS': 'CHALETS',
    'COMUNIDAD': 'COMUNIDAD',
    'ESTANCIAS': 'EST',
    'EXTENSION': 'EXT',
    'EXTENSIONES': 'EXT',
    'HACIENDA': 'HACIENDA',
    'JARDINES': 'JARD',
    'INDUSTRIAL': 'IND',
    'LOMA': 'LOMA',
    'LOMAS': 'LOMAS',
    'MANSIONES': 'MANS',
    'PARQUE': 'PARQ',
    'PARCELA': 'PARCELA',
    'PARCELAS': 'PARCELAS',
    'PASEO': 'PASEO',
    'PRADERA': 'PRADERA',
    'PORTAL': 'PORTAL',
    'PORTALES': 'PORTALES',
    'QUINTAS': 'QUINTAS',
    'RESIDENCIAL': 'RES',
    'REPARTO': 'REPTO',
    'RIBERAS': 'RIBERAS',
    'SECTOR': 'SECT',
    'TERRAZA': 'TERR',
    'VALLE': 'VALLE',
    'VILLA': 'VILLA',
    'VILLAS': 'VILLAS',
    'VISTA': 'VISTA',
    'VISTAS': 'VISTAS',
}

DIACRITICS = {
    'À': 'A',
    'Á': 'A',
    'Â': 'A',
    'Ã': 'A',
    'Ä': 'A',
    'Å': 'A',
    'Æ': 'A',
    'Ç': 'C',
    'È': 'E',
    'É': 'E',
    'Ê': 'E',
    'Ë': 'E',
    'Ì': 'I',
    'Í': 'I',
    'Î': 'I',
    'Ï': 'I',
    'Ð': 'E',
    'Ñ': 'N',
    'Ò': 'O',
    'Ó': 'O',
    'Ô': 'O',
    'Õ': 'O',
    'Ö': 'O',
    'Ø': 'O',
    'Ù': 'U',
    'Ú': 'U',
    'Û': 'U',
    'Ü': 'U',
    'Ý': 'Y',
    'Þ': 'P',
    'ß': 'S',
    'à': 'A',
    'á': 'A',
    'â': 'A',
    'ã': 'A',
    'ä': 'A',
    'å': 'A',
    'æ': 'A',
    'ç': 'C',
    'è': 'E',
    'é': 'E',
    'ê': 'E',
    'ë': 'E',
    'ì': 'I',
    'í': 'I',
    'î': 'I',
    'ï': 'I',
    'ð': 'E',
    'ñ': 'N',
    'ò': 'O',
    'ó': 'O',
    'ô': 'O',
    'õ': 'O',
    'ö': 'O',
    'ø': 'O',
    'ù': 'U',
    'ú': 'U',
    'û': 'U',
    'ü': 'U',
    'ý': 'Y',
    'þ': 'P',
    'ÿ': 'Y',
    'Œ': 'O',
    'œ': 'O',
    'Š': 'S',
    'š': 'S',
    'Ÿ': 'Y',
}

COUNTRIES = {
    'AFGHANISTAN',
    'ALBANIA',
    'ALGERIA',
    'AMERICAN SAMOA',
    'ANDORRA',
    'ANGOLA',
    'ANGUILLA',
    'ANTARCTICA',
    'ANTIGUA AND BARBUDA',
    'ARAB REPUBLIC OF EGYPT',
    'ARGENTINA',
    'ARGENTINE REPUBLIC',
    'ARMENIA',
    'ARUBA',
    'AUSTRALIA',
    'AUSTRIA',
    'AZERBAIJAN',
    'BAHAMAS',
    'BAHRAIN',
    'BAILIWICK OF GUERNSEY',
    'BAILIWICK OF JERSEY',
    'BANGLADESH',
    'BARBADOS',
    'BELARUS',
    'BELGIUM',
    'BELIZE',
    'BENIN',
    'BERMUDA',
    'BHUTAN',
    'BOLIVARIAN REPUBLIC OF VENEZUELA',
    'BOLIVIA',
    'BONAIRE, SINT EUSTATIUS AND SABA',
    'BOSNIA AND HERZEGOVINA',
    'BOTSWANA',
    'BOUVET ISLAND',
    'BRAZIL',
    'BRITISH INDIAN OCEAN TERRITORY',
    'BRITISH VIRGIN ISLANDS',
    'BRUNEI',
    'BULGARIA',
    'BURKINA FASO',
    'BURUNDI',
    'CAMBODIA',
    'CAMEROON',
    'CANADA',
    'CAPE VERDE',
    'CARIBBEAN NETHERLANDS',
    'CAYMAN ISLANDS',
    'CENTRAL AFRICAN REPUBLIC',
    'CHAD',
    'CHILE',
    'CHINA',
    'CHRISTMAS ISLAND',
    'CO-OPERATIVE REPUBLIC OF GUYANA',
    'COCOS (KEELING) ISLANDS',
    'COLLECTIVITY OF SAINT BARTHÉLEMY',
    'COLOMBIA',
    'COMMONWEALTH OF AUSTRALIA',
    'COMMONWEALTH OF DOMINICA',
    'COMMONWEALTH OF PUERTO RICO',
    'COMMONWEALTH OF THE BAHAMAS',
    'COMMONWEALTH OF THE NORTHERN MARIANA ISLANDS',
    'COMOROS',
    'CONGO',
    'COOK ISLANDS',
    'COSTA RICA',
    'COUNTRY OF CURAÇAO',
    'CROATIA',
    'CUBA',
    'CURAÇAO',
    'CYPRUS',
    'CZECH REPUBLIC',
    'CZECHIA',
    "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    'DEMOCRATIC REPUBLIC OF SÃO TOMÉ AND PRÍNCIPE',
    'DEMOCRATIC REPUBLIC OF THE CONGO',
    'DEMOCRATIC REPUBLIC OF TIMOR-LESTE',
    'DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA',
    'DENMARK',
    'DEPARTMENT OF MAYOTTE',
    'DJIBOUTI',
    'DOMINICA',
    'DOMINICAN REPUBLIC',
    'DR CONGO',
    'ECUADOR',
    'EGYPT',
    'EL SALVADOR',
    'ENGLAND',
    'EQUATORIAL GUINEA',
    'ERITREA',
    'ESTONIA',
    'ESWATINI',
    'ETHIOPIA',
    'FALKLAND ISLANDS',
    'FAROE ISLANDS',
    'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
    'FEDERAL DEMOCRATIC REPUBLIC OF NEPAL',
    'FEDERAL REPUBLIC OF GERMANY',
    'FEDERAL REPUBLIC OF NIGERIA',
    'FEDERAL REPUBLIC OF SOMALIA',
    'FEDERATED STATES OF MICRONESIA',
    'FEDERATION OF SAINT CHRISTOPHER AND NEVIS',
    'FEDERATIVE REPUBLIC OF BRAZIL',
    'FIJI',
    'FINLAND',
    'FRANCE',
    'FRENCH GUIANA',
    'FRENCH POLYNESIA',
    'FRENCH REPUBLIC',
    'FRENCH SOUTHERN AND ANTARCTIC LANDS',
    'GABON',
    'GABONESE REPUBLIC',
    'GAMBIA',
    'GEORGIA',
    'GERMANY',
    'GHANA',
    'GIBRALTAR',
    'GRAND DUCHY OF LUXEMBOURG',
    'GREAT BRITAIN',
    'GREECE',
    'GREENLAND',
    'GRENADA',
    'GUADELOUPE',
    'GUAM',
    'GUATEMALA',
    'GUERNSEY',
    'GUIANA',
    'GUINEA',
    'GUINEA-BISSAU',
    'GUYANA',
    'HAITI',
    'HASHEMITE KINGDOM OF JORDAN',
    'HEARD ISLAND AND MCDONALD ISLANDS',
    'HELLENIC REPUBLIC',
    'HONDURAS',
    'HONG KONG',
    "HONG KONG SPECIAL ADMINISTRATIVE REGION OF THE PEOPLE'S REPUBLIC OF CHINA",
    'HUNGARY',
    'ICELAND',
    'INDEPENDENT AND SOVEREIGN REPUBLIC OF KIRIBATI',
    'INDEPENDENT STATE OF PAPUA NEW GUINEA',
    'INDEPENDENT STATE OF SAMOA',
    'INDIA',
    'INDONESIA',
    'IRAN',
    'IRAQ',
    'IRELAND',
    'ISLAMIC REPUBLIC OF AFGHANISTAN',
    'ISLAMIC REPUBLIC OF IRAN',
    'ISLAMIC REPUBLIC OF MAURITANIA',
    'ISLAMIC REPUBLIC OF PAKISTAN',
    'ISLE OF MAN',
    'ISRAEL',
    'ITALIAN REPUBLIC',
    'ITALY',
    'IVORY COAST',
    'JAMAICA',
    'JAPAN',
    'JERSEY',
    'JORDAN',
    'KAZAKHSTAN',
    'KENYA',
    'KINGDOM OF BAHRAIN',
    'KINGDOM OF BELGIUM',
    'KINGDOM OF BHUTAN',
    'KINGDOM OF CAMBODIA',
    'KINGDOM OF DENMARK',
    'KINGDOM OF ESWATINI',
    'KINGDOM OF LESOTHO',
    'KINGDOM OF MOROCCO',
    'KINGDOM OF NORWAY',
    'KINGDOM OF SAUDI ARABIA',
    'KINGDOM OF SPAIN',
    'KINGDOM OF SWEDEN',
    'KINGDOM OF THAILAND',
    'KINGDOM OF THE NETHERLANDS',
    'KINGDOM OF TONGA',
    'KIRIBATI',
    'KOSOVO',
    'KUWAIT',
    'KYRGYZ REPUBLIC',
    'KYRGYZSTAN',
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    'LAOS',
    'LATVIA',
    'LEBANESE REPUBLIC',
    'LEBANON',
    'LESOTHO',
    'LIBERIA',
    'LIBYA',
    'LIECHTENSTEIN',
    'LITHUANIA',
    'LUXEMBOURG',
    "MACAO SPECIAL ADMINISTRATIVE REGION OF THE PEOPLE'S REPUBLIC OF CHINA",
    'MACAU',
    'MADAGASCAR',
    'MALAWI',
    'MALAYSIA',
    'MALDIVES',
    'MALI',
    'MALTA',
    'MARSHALL ISLANDS',
    'MARTINIQUE',
    'MAURITANIA',
    'MAURITIUS',
    'MAYOTTE',
    'MEXICO',
    'MICRONESIA',
    'MOLDOVA',
    'MONACO',
    'MONGOLIA',
    'MONTENEGRO',
    'MONTSERRAT',
    'MOROCCO',
    'MOST SERENE REPUBLIC OF SAN MARINO',
    'MOZAMBIQUE',
    'MYANMAR',
    'NAMIBIA',
    'NATION OF BRUNEI, ABODE OF PEACE',
    'NAURU',
    'NEPAL',
    'NETHERLANDS',
    'NEW CALEDONIA',
    'NEW ZEALAND',
    'NICARAGUA',
    'NIGER',
    'NIGERIA',
    'NIUE',
    'NORFOLK ISLAND',
    'NORTH KOREA',
    'NORTH MACEDONIA',
    'NORTHERN MARIANA ISLANDS',
    'NORWAY',
    'OMAN',
    'ORIENTAL REPUBLIC OF URUGUAY',
    'PAKISTAN',
    'PALAU',
    'PALESTINE',
    'PANAMA',
    'PAPUA NEW GUINEA',
    'PARAGUAY',
    "PEOPLE'S DEMOCRATIC REPUBLIC OF ALGERIA",
    "PEOPLE'S REPUBLIC OF BANGLADESH",
    "PEOPLE'S REPUBLIC OF CHINA",
    'PERU',
    'PHILIPPINES',
    'PITCAIRN GROUP OF ISLANDS',
    'PITCAIRN ISLANDS',
    'PLURINATIONAL STATE OF BOLIVIA',
    'POLAND',
    'PORTUGAL',
    'PORTUGUESE REPUBLIC',
    'PRINCIPALITY OF ANDORRA',
    'PRINCIPALITY OF LIECHTENSTEIN',
    'PRINCIPALITY OF MONACO',
    'PUERTO RICO',
    'QATAR',
    'REPUBLIC OF ALBANIA',
    'REPUBLIC OF ANGOLA',
    'REPUBLIC OF ARMENIA',
    'REPUBLIC OF AUSTRIA',
    'REPUBLIC OF AZERBAIJAN',
    'REPUBLIC OF BELARUS',
    'REPUBLIC OF BENIN',
    'REPUBLIC OF BOTSWANA',
    'REPUBLIC OF BULGARIA',
    'REPUBLIC OF BURUNDI',
    'REPUBLIC OF CABO VERDE',
    'REPUBLIC OF CAMEROON',
    'REPUBLIC OF CHAD',
    'REPUBLIC OF CHILE',
    'REPUBLIC OF CHINA (TAIWAN)',
    'REPUBLIC OF COLOMBIA',
    'REPUBLIC OF COSTA RICA',
    'REPUBLIC OF CROATIA',
    'REPUBLIC OF CUBA',
    'REPUBLIC OF CYPRUS',
    "REPUBLIC OF CÔTE D'IVOIRE",
    'REPUBLIC OF DJIBOUTI',
    'REPUBLIC OF ECUADOR',
    'REPUBLIC OF EL SALVADOR',
    'REPUBLIC OF EQUATORIAL GUINEA',
    'REPUBLIC OF ESTONIA',
    'REPUBLIC OF FIJI',
    'REPUBLIC OF FINLAND',
    'REPUBLIC OF GHANA',
    'REPUBLIC OF GUATEMALA',
    'REPUBLIC OF GUINEA',
    'REPUBLIC OF GUINEA-BISSAU',
    'REPUBLIC OF HAITI',
    'REPUBLIC OF HONDURAS',
    'REPUBLIC OF INDIA',
    'REPUBLIC OF INDONESIA',
    'REPUBLIC OF IRAQ',
    'REPUBLIC OF IRELAND',
    'REPUBLIC OF KAZAKHSTAN',
    'REPUBLIC OF KENYA',
    'REPUBLIC OF KOREA',
    'REPUBLIC OF KOSOVO',
    'REPUBLIC OF LATVIA',
    'REPUBLIC OF LIBERIA',
    'REPUBLIC OF LITHUANIA',
    'REPUBLIC OF MADAGASCAR',
    'REPUBLIC OF MALAWI',
    'REPUBLIC OF MALI',
    'REPUBLIC OF MALTA',
    'REPUBLIC OF MAURITIUS',
    'REPUBLIC OF MOLDOVA',
    'REPUBLIC OF MOZAMBIQUE',
    'REPUBLIC OF NAMIBIA',
    'REPUBLIC OF NAURU',
    'REPUBLIC OF NICARAGUA',
    'REPUBLIC OF NIGER',
    'REPUBLIC OF NORTH MACEDONIA',
    'REPUBLIC OF PALAU',
    'REPUBLIC OF PANAMA',
    'REPUBLIC OF PARAGUAY',
    'REPUBLIC OF PERU',
    'REPUBLIC OF POLAND',
    'REPUBLIC OF RWANDA',
    'REPUBLIC OF SENEGAL',
    'REPUBLIC OF SERBIA',
    'REPUBLIC OF SEYCHELLES',
    'REPUBLIC OF SIERRA LEONE',
    'REPUBLIC OF SINGAPORE',
    'REPUBLIC OF SLOVENIA',
    'REPUBLIC OF SOUTH AFRICA',
    'REPUBLIC OF SOUTH SUDAN',
    'REPUBLIC OF SURINAME',
    'REPUBLIC OF TAJIKISTAN',
    'REPUBLIC OF THE CONGO',
    'REPUBLIC OF THE GAMBIA',
    'REPUBLIC OF THE MALDIVES',
    'REPUBLIC OF THE MARSHALL ISLANDS',
    'REPUBLIC OF THE PHILIPPINES',
    'REPUBLIC OF THE SUDAN',
    'REPUBLIC OF THE UNION OF MYANMAR',
    'REPUBLIC OF TRINIDAD AND TOBAGO',
    'REPUBLIC OF TÜRKIYE',
    'REPUBLIC OF UGANDA',
    'REPUBLIC OF UZBEKISTAN',
    'REPUBLIC OF VANUATU',
    'REPUBLIC OF YEMEN',
    'REPUBLIC OF ZAMBIA',
    'REPUBLIC OF ZIMBABWE',
    'ROMANIA',
    'RUSSIA',
    'RUSSIAN FEDERATION',
    'RWANDA',
    'RÉUNION',
    'RÉUNION ISLAND',
    'SAHRAWI ARAB DEMOCRATIC REPUBLIC',
    'SAINT BARTHÉLEMY',
    'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    'SAINT KITTS AND NEVIS',
    'SAINT LUCIA',
    'SAINT MARTIN',
    'SAINT PIERRE AND MIQUELON',
    'SAINT VINCENT AND THE GRENADINES',
    'SAMOA',
    'SAN MARINO',
    'SAUDI ARABIA',
    'SCOTLAND',
    'SENEGAL',
    'SERBIA',
    'SEYCHELLES',
    'SIERRA LEONE',
    'SINGAPORE',
    'SINT MAARTEN',
    'SLOVAK REPUBLIC',
    'SLOVAKIA',
    'SLOVENIA',
    'SOCIALIST REPUBLIC OF VIETNAM',
    'SOLOMON ISLANDS',
    'SOMALIA',
    'SOUTH AFRICA',
    'SOUTH GEORGIA',
    'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    'SOUTH KOREA',
    'SOUTH SUDAN',
    'SPAIN',
    'SRI LANKA',
    'STATE OF ERITREA',
    'STATE OF ISRAEL',
    'STATE OF KUWAIT',
    'STATE OF LIBYA',
    'STATE OF PALESTINE',
    'STATE OF QATAR',
    'SUDAN',
    'SULTANATE OF OMAN',
    'SURINAME',
    'SVALBARD AND JAN MAYEN',
    'SVALBARD OG JAN MAYEN',
    'SWEDEN',
    'SWISS CONFEDERATION',
    'SWITZERLAND',
    'SYRIA',
    'SYRIAN ARAB REPUBLIC',
    'SÃO TOMÉ AND PRÍNCIPE',
    'TAIWAN',
    'TAJIKISTAN',
    'TANZANIA',
    'TERRITORY OF CHRISTMAS ISLAND',
    'TERRITORY OF NORFOLK ISLAND',
    'TERRITORY OF THE COCOS (KEELING) ISLANDS',
    'TERRITORY OF THE FRENCH SOUTHERN AND ANTARCTIC LANDS',
    'TERRITORY OF THE WALLIS AND FUTUNA ISLANDS',
    'THAILAND',
    'TIMOR-LESTE',
    'TOGO',
    'TOGOLESE REPUBLIC',
    'TOKELAU',
    'TONGA',
    'TRINIDAD AND TOBAGO',
    'TUNISIA',
    'TUNISIAN REPUBLIC',
    'TURKMENISTAN',
    'TURKS AND CAICOS ISLANDS',
    'TUVALU',
    'TÜRKIYE',
    'UGANDA',
    'UK',
    'UKRAINE',
    'UNION OF THE COMOROS',
    'UNITED ARAB EMIRATES',
    'UNITED KINGDOM',
    'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
    'UNITED MEXICAN STATES',
    'UNITED REPUBLIC OF TANZANIA',
    'UNITED STATES',
    'UNITED STATES MINOR OUTLYING ISLANDS',
    'UNITED STATES OF AMERICA',
    'UNITED STATES VIRGIN ISLANDS',
    'URUGUAY',
    'USA',
    'UZBEKISTAN',
    'VANUATU',
    'VATICAN CITY',
    'VATICAN CITY STATE',
    'VENEZUELA',
    'VIETNAM',
    'VIRGIN ISLANDS',
    'VIRGIN ISLANDS OF THE UNITED STATES',
    'WALES',
    'WALLIS AND FUTUNA',
    'WESTERN SAHARA',
    'YEMEN',
    'ZAMBIA',
    'ZIMBABWE',
    'ÅLAND ISLANDS',
}
