import http.client

'''
  Log entry schemas used for integration tests
  See the following for information about the JSON Schema vocabulary: https://json-schema.org/
'''

LOG_MIDDLEWARE_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "elapsed": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "path": {"pattern": ".+"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK, http.client.MOVED_PERMANENTLY]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "elapsed", "request_uuid",
                 "path", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_POST_TOKEN_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "elapsed": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "path": {"pattern": "/v1/o/token"},
        "request_method": {"pattern": "POST"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "app_id": {"type": "string"},
        "app_name": {"pattern": "TestApp"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_share_demographic_scopes": {"pattern": "^True$"},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "elapsed", "request_uuid", "path",
                 "request_method", "request_scheme", "response_code",
                 "app_id", "app_name", "auth_uuid", "auth_client_id",
                 "auth_app_id", "auth_app_name",
                 "auth_app_data_access_type",
                 "auth_require_demographic_scopes", ]
}

LOG_MIDDLEWARE_TESTCLIENT_AUTHLINK_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "path": {"pattern": ".+"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "path", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_AUTH_START_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "location": {"pattern": ".+"},
        "app_id": {"type": "string"},
        "app_name": {"pattern": "TestApp"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
        "req_qparam_client_id": {"type": "string"},
        "req_qparam_lang": {"type": "string"},
        "req_qparam_response_type": {"pattern": "code"},
        "req_app_name": {"pattern": "TestApp"},
        "req_app_id": {"type": "number"},
        "path": {"pattern": "/v1/o/authorize/"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.FOUND]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "location", "app_id", "app_name", "auth_uuid", "auth_client_id",
                 "auth_app_data_access_type",
                 "auth_app_id", "auth_app_name", "auth_require_demographic_scopes",
                 "req_qparam_client_id", "req_qparam_response_type", "req_app_name", "req_app_id",
                 "path", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_MEDICARE_LOGIN_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "location": {"pattern": ".+"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
        "path": {"pattern": "/mymedicare/login"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.FOUND]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "location", "auth_uuid", "auth_client_id", "auth_app_id",
                 "auth_app_data_access_type",
                 "auth_app_name", "auth_require_demographic_scopes",
                 "path", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_MEDICARE_CALLBACK_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "location": {"pattern": ".+"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_crosswalk_action": {"enum": ["R", "C"]},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
        "req_user_id": {"type": "number"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "path": {"pattern": "/mymedicare/sls-callback"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.FOUND]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "location", "auth_uuid", "auth_client_id", "auth_app_id", "auth_app_name", "auth_require_demographic_scopes",
                 "auth_app_data_access_type",
                 "req_user_id", "req_user_username", "req_fhir_id",
                 "path", "user", "fhir_id", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_AUTHORIZE_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "location": {"pattern": ".*"},
        "app_id": {"type": "string"},
        "app_name": {"pattern": "TestApp"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_crosswalk_action": {"enum": ["R", "C"]},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
        "req_qparam_client_id": {"type": "string"},
        "req_qparam_lang": {"type": "string", "default": "en"},
        "req_qparam_response_type": {"pattern": "code"},
        "req_app_name": {"pattern": "TestApp"},
        "req_app_id": {"type": "number"},
        "path": {"pattern": "/v1/o/authorize/.+"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "location", "app_id", "app_name", "auth_uuid", "auth_client_id", "auth_app_id", "auth_app_name",
                 "auth_app_data_access_type",
                 "auth_crosswalk_action", "auth_require_demographic_scopes", "req_qparam_client_id",
                 "req_qparam_response_type", "req_app_name", "req_app_id",
                 "path", "user", "fhir_id", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_ACCESS_GRANT_EVENT_SCHEMA = {
    "title": "MiddlewareLogEventSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "location": {"pattern": ".+"},
        "app_id": {"type": "string"},
        "app_name": {"pattern": "TestApp"},
        "auth_uuid": {"type": "string"},
        "auth_client_id": {"type": "string"},
        "auth_app_id": {"type": "string"},
        "auth_app_name": {"pattern": "TestApp"},
        "auth_app_data_access_type": {"pattern": "THIRTEEN_MONTH"},
        "auth_crosswalk_action": {"enum": ["R", "C"]},
        "auth_require_demographic_scopes": {"pattern": "^True$"},
        "req_redirect_uri": {"type": "string"},
        "req_scope": {"type": "string"},
        "req_share_demographic_scopes": {"pattern": "^True$"},
        "req_allow": {"pattern": "Connect"},
        "req_user_id": {"type": "integer"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "req_qparam_client_id": {"type": "string"},
        "req_qparam_lang": {"type": "string"},
        "req_qparam_response_type": {"pattern": "code"},
        "req_app_name": {"pattern": "TestApp"},
        "req_app_id": {"type": "number"},
        "path": {"pattern": "/v1/o/authorize/.+"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "request_method": {"pattern": "POST"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.FOUND]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "location", "app_id", "app_name", "auth_uuid", "auth_client_id", "auth_app_id", "auth_app_name",
                 "auth_app_data_access_type",
                 "auth_crosswalk_action", "auth_require_demographic_scopes",
                 "req_redirect_uri", "req_scope", "req_user_username", "req_fhir_id",
                 "req_qparam_client_id", "req_qparam_response_type", "req_app_name", "req_app_id",
                 "path", "user", "fhir_id", "request_method", "request_scheme", "response_code"]
}

LOG_MIDDLEWARE_TESTCLIENT_FHIR_READ_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "path": {"pattern": "/testclient/.+"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code", "path"]
}

LOG_MIDDLEWARE_TESTCLIENT_FHIR_SEARCH_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "path": {"pattern": "/testclient/.+"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code", "path"]
}

LOG_MIDDLEWARE_TESTCLIENT_FHIR_NAVIGATION_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "path": {"pattern": "/testclient/.+"},
        "req_qparam__count": {"type": "string"},
        "req_qparam_patient": {"type": "string"},
        "req_qparam_beneficiary": {"type": "string"},
        "req_qparam_startindex": {"type": "string"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code", "path",
                 "req_qparam__count", "req_qparam_startindex"]
}

LOG_MIDDLEWARE_FHIR_SEARCH_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "req_user_id": {"type": "integer"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "req_qparam_format": {"pattern": "json"},
        "req_qparam_patient": {"type": "string"},
        "req_qparam_beneficiary": {"type": "string"},
        "path": {"pattern": "/v1/fhir/.+"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "access_token_scopes": {"type": "string"},
        "access_token_id": {"type": "number"},
        "app_require_demographic_scopes": {"type": "boolean"},
        "user_id": {"type": "integer"},
        "user_username": {"type": "string"},
        "fhir_bundle_type": {"pattern": "searchset|null"},
        "fhir_resource_id": {"type": "string"},
        "fhir_resource_type": {"pattern": "Bundle|Patient|Coverage|ExplanationOfBenefit"},
        "fhir_attribute_count": {"type": "number"},
        "fhir_entry_count": {"type": ["number", "null"]},
        "fhir_total": {"type": ["number", "null"]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code",
                 "req_user_id", "req_user_username", "req_fhir_id", "req_qparam_format",
                 "path", "user", "fhir_id", "access_token_scopes", "access_token_id", "app_require_demographic_scopes",
                 "user_id", "user_username", "fhir_bundle_type", "fhir_resource_id", "fhir_resource_type",
                 "fhir_attribute_count", "fhir_entry_count", "fhir_total"]
}

LOG_MIDDLEWARE_FHIR_NAVIGATION_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "req_user_id": {"type": "integer"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "req_qparam__count": {"type": "string"},
        "req_qparam_format": {"pattern": "json"},
        "req_qparam_patient": {"type": "string"},
        "req_qparam_beneficiary": {"type": "string"},
        "req_qparam_startindex": {"type": "string"},
        "path": {"pattern": "/v1/fhir/.+"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "access_token_scopes": {"type": "string"},
        "access_token_id": {"type": "number"},
        "app_require_demographic_scopes": {"type": "boolean"},
        "user_id": {"type": "integer"},
        "user_username": {"type": "string"},
        "fhir_bundle_type": {"pattern": "searchset|null"},
        "fhir_resource_id": {"type": "string"},
        "fhir_resource_type": {"pattern": "Bundle|Patient|Coverage|ExplanationOfBenefit"},
        "fhir_attribute_count": {"type": "number"},
        "fhir_entry_count": {"type": ["number", "null"]},
        "fhir_total": {"type": ["number", "null"]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr",
                 "request_uuid", "request_method", "request_scheme", "response_code",
                 "req_user_id", "req_user_username", "req_fhir_id",
                 "req_qparam__count", "req_qparam_format", "req_qparam_startindex",
                 "path", "user", "fhir_id", "access_token_scopes", "access_token_id", "app_require_demographic_scopes",
                 "user_id", "user_username", "fhir_bundle_type", "fhir_resource_id", "fhir_resource_type",
                 "fhir_attribute_count", "fhir_entry_count", "fhir_total"]
}

LOG_MIDDLEWARE_FHIR_READ_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "req_user_id": {"type": "integer"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "path": {"pattern": "/v1/fhir/.+"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "access_token_scopes": {"type": "string"},
        "access_token_id": {"type": "number"},
        "app_require_demographic_scopes": {"type": "boolean"},
        "user_id": {"type": "integer"},
        "user_username": {"type": "string"},
        "fhir_bundle_type": {"pattern": "searchset|null"},
        "fhir_resource_id": {"type": "string"},
        "fhir_resource_type": {"pattern": "Bundle|Patient|Coverage|ExplanationOfBenefit"},
        "fhir_attribute_count": {"type": "number"},
        "fhir_entry_count": {"type": ["number", "null"]},
        "fhir_total": {"type": ["number", "null"]},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr",
                 "request_uuid", "request_method", "request_scheme", "response_code",
                 "req_user_id", "req_user_username", "req_fhir_id",
                 "path", "user", "fhir_id", "access_token_scopes", "access_token_id", "app_require_demographic_scopes",
                 "user_id", "user_username", "fhir_bundle_type", "fhir_resource_id", "fhir_resource_type",
                 "fhir_attribute_count", "fhir_entry_count", "fhir_total"]
}

LOG_MIDDLEWARE_FHIR_USERINFO_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "req_user_id": {"type": "integer"},
        "req_user_username": {"type": "string"},
        "req_fhir_id": {"type": "string"},
        "path": {"pattern": "/v1/connect/userinfo"},
        "user": {"type": "string"},
        "fhir_id": {"type": "string"},
        "access_token_scopes": {"type": "string"},
        "access_token_id": {"type": "number"},
        "app_require_demographic_scopes": {"type": "boolean"},
        "user_id": {"type": "integer"},
        "user_username": {"type": "string"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code",
                 "req_user_id", "req_user_username", "req_fhir_id",
                 "path", "user", "fhir_id", "access_token_scopes",
                 "access_token_id", "app_require_demographic_scopes",
                 "user_id", "user_username"]
}

LOG_MIDDLEWARE_TESTCLIENT_MISCINFO_EVENT_SCHEMA = {
    "title": "RequestResponseLogSchema",
    "type": "object",
    "properties": {
        "type": {"pattern": "request_response_middleware"},
        "size": {"type": "integer"},
        "start_time": {"type": "number"},
        "end_time": {"type": "number"},
        "ip_addr": {"type": "string", "format": "ip-address"},
        "request_uuid": {"type": "string", "format": "uuid"},
        "request_method": {"pattern": "GET"},
        "request_scheme": {"pattern": "http"},
        "response_code": {"type": "integer", "enum": [http.client.OK]},
        "path": {"pattern": "/testclient/userinfo|/testclient/openidConfig|/testclient/metadata|/testclient/restart"},
    },
    "required": ["type", "size", "start_time", "end_time", "ip_addr", "request_uuid",
                 "request_method", "request_scheme", "response_code", "path"]
}
