# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('json_schema', models.TextField(default='{}', help_text='{} indicates no schema.', max_length=5120)),
                ('get', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='get')),
                ('put', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='put')),
                ('create', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='create')),
                ('read', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='read')),
                ('vread', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='vread')),
                ('update', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='update')),
                ('delete', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='delete')),
                ('search', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='search')),
                ('history', models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='_history')),
            ],
        ),
    ]
