# Generated by Django 2.2.22 on 2021-05-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bluebutton', '0001_squashed_0006_auto_20210513_1812'),
    ]

    operations = [
    ]
