# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_url', models.URLField(blank=True, help_text='Exclude the resource. eg. <b>https://fhirserver.com/fhir/Patient/</b> is entered as <b>https://fhirserver.com/fhir/</b></br>Leave blank to accept system default.', verbose_name='Default FHIR URL with terminating /')),
            ],
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='override_search',
            field=models.BooleanField(default=False, help_text="Do search parameters need to be filtered to avoid revealing other people's data?"),
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='override_url_id',
            field=models.BooleanField(default=False, help_text='Does this resource need to mask the id in the url?'),
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='search_add',
            field=models.TextField(blank=True, default='', help_text='list of keys that need to be added to search parameters to filter information that is returned. eg. <b>Patient=%PATIENT%</b>', max_length=200),
        ),
        migrations.AddField(
            model_name='supportedresourcetype',
            name='search_block',
            field=models.TextField(blank=True, default='', help_text='list of values that need to be removed from search parameters. eg. <b>Patient</b>', max_length=5120),
        ),
        migrations.AddField(
            model_name='resourcerouter',
            name='resource_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.SupportedResourceType'),
        ),
    ]
