# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20160917_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerouter',
            old_name='fhir_url',
            new_name='fhir_path',
        ),
    ]
