# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160917_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedresourcetype',
            name='patch',
            field=models.BooleanField(default=False, help_text='FHIR Interaction Type', verbose_name='patch'),
        ),
    ]
