# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_supportedresourcetype_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedresourcetype',
            name='secure_access',
            field=models.BooleanField(default=True, help_text='Login required to accessthis resource', verbose_name='Secured resource'),
        ),
    ]
