# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_supportedresourcetype_secure_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedresourcetype',
            name='secure_access',
            field=models.BooleanField(default=True, help_text='Login required to access this resource', verbose_name='Secured resource'),
        ),
    ]
