# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20170423_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedresourcetype',
            name='resourceType',
            field=models.CharField(db_index=True, default='define_resourceType', max_length=250),
            preserve_default=False,
        ),
    ]
