# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20170501_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerouter',
            name='supported_resource',
        ),
        migrations.AddField(
            model_name='resourcerouter',
            name='supported_resource',
            field=models.ManyToManyField(to='server.SupportedResourceType'),
        ),
    ]
