# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20170501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedresourcetype',
            name='fhir_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ResourceRouter'),
        ),
        migrations.AlterField(
            model_name='supportedresourcetype',
            name='resourceType',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Actual FHIR Resource Type'),
        ),
        migrations.AlterField(
            model_name='supportedresourcetype',
            name='resource_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='unique Resource name in this table'),
        ),
    ]
