# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20170713_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerouter',
            name='supported_resource',
        ),
        migrations.AddField(
            model_name='resourcerouter',
            name='server_address',
            field=models.URLField(default='http://52.72.172.54:8080', verbose_name='Server Name in URL form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerouter',
            name='server_path',
            field=models.CharField(default='/', max_length=254, verbose_name='path to API with terminating /'),
        ),
        migrations.AddField(
            model_name='resourcerouter',
            name='server_release',
            field=models.CharField(default='v1/fhir/', max_length=254, verbose_name='FHIR release with terminating /'),
        ),
        migrations.AlterField(
            model_name='supportedresourcetype',
            name='fhir_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ResourceRouter'),
        ),
    ]
