# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20170713_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerouter',
            name='supported_resource',
            field=models.ManyToManyField(to='server.SupportedResourceType'),
        ),
    ]
