# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_resourcerouter_supported_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerouter',
            name='supported_resource',
        ),
    ]
