# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_resourcerouter_supported_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerouter',
            name='server_search_expiry',
            field=models.IntegerField(default=1800, verbose_name='Search expires in seconds'),
        ),
    ]
