# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_resourcerouter_server_search_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerouter',
            name='wait_time',
            field=models.IntegerField(blank=True, default=30, help_text='Seconds to wait before timing out a call to this server.', verbose_name='Server wait time (Seconds)'),
        ),
    ]
