# Generated by Django 2.2.22 on 2021-05-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0006_auto_20210513_1812'),
        ('server', '0017_resourcerouter_wait_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedresourcetype',
            name='fhir_source',
        ),
        migrations.DeleteModel(
            name='ResourceRouter',
        ),
        migrations.DeleteModel(
            name='SupportedResourceType',
        ),
    ]
