version: '3'
services:
  hl7_validator_service:
    image: infernocommunity/inferno-resource-validator
    environment:
      # Defines how long validator sessions last if unused, in minutes:
      # Negative values mean sessions never expire, 0 means sessions immediately expire
      SESSION_CACHE_DURATION: -1
    volumes:
      - ./data/igs:/app/igs
      # To let the service share your local FHIR package cache,
      # uncomment the below line
      # - ~/.fhir:/home/ktor/.fhir
  # validator_service:
  #   image: infernocommunity/fhir-validator-service
  #   # Update this path to match your directory structure
  #   volumes:
  #     - ./data/igs:/home/igs
  # fhir_validator_app:
  #   image: infernocommunity/fhir-validator-app
  #   depends_on:
  #     - validator_service
  #   environment:
  #     EXTERNAL_VALIDATOR_URL: http://localhost/validatorapi
  #     VALIDATOR_BASE_PATH: /validator
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.background.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - hl7_validator_service
      # - fhir_validator_app
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
