# Generated by Django 2.2.22 on 2021-05-15 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=uuid.uuid4, max_length=40)),
                ('expires', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFACode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=4)),
                ('mode', models.CharField(choices=[('', 'None'), ('EMAIL', 'Email'), ('SMS', 'Text Message (SMS)')], default='', max_length=5)),
                ('valid', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(blank=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36)),
                ('tries_counter', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ValidPasswordResetKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_password_key', models.CharField(blank=True, max_length=50)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('organization', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('added', models.DateField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('BEN', 'Beneficiary'), ('DEV', 'Developer')], default='DEV', max_length=3)),
                ('invite_sent', models.BooleanField(default=False)),
                ('issue_invite', models.CharField(choices=[('', 'Not Set'), ('YES', 'Yes - Send Invite'), ('NO', 'NO - Do not send invite'), ('DONE', 'Invite has been sent')], default='', max_length=4)),
            ],
            options={
                'verbose_name': 'Invite Request',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('loa', models.CharField(blank=True, choices=[('', 'Undefined'), ('1', 'LOA-1'), ('2', 'LOA-2'), ('3', 'LOA-3'), ('4', 'LOA-4')], default='2', help_text='Legacy and Deprecated. Using IAL AAL is recommended.', max_length=1, verbose_name='Level of Assurance')),
                ('user_type', models.CharField(choices=[('BEN', 'Beneficiary'), ('DEV', 'Developer')], default='DEV', max_length=5)),
                ('access_key_id', models.CharField(blank=True, max_length=20)),
                ('access_key_secret', models.CharField(blank=True, max_length=40)),
                ('access_key_reset', models.BooleanField(default=False, blank=True, help_text='Check this box to issue a new access key. Doing so invalidates the existing key.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('create_applications', models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to register applications.')),
                ('password_reset_answer_1', models.CharField(blank=True, default='', max_length=50)),
                ('password_reset_answer_2', models.CharField(blank=True, default='', max_length=50)),
                ('password_reset_answer_3', models.CharField(blank=True, default='', max_length=50)),
                ('password_reset_question_1', models.CharField(choices=[('1', 'What is your favorite color?'), ('2', 'What is your favorite vegetable?'), ('3', 'What is your favorite movie?')], default='1', max_length=1)),
                ('password_reset_question_2', models.CharField(choices=[('1', 'What was the name of your best friend from childhood?'), ('2', 'What was the name of your elementary school?'), ('3', 'What was the name of your favorite pet?')], default='1', max_length=1)),
                ('password_reset_question_3', models.CharField(choices=[('1', 'What was the make of your first automobile?'), ('2', "What was your maternal grandmother's maiden name?"), ('3', "What was your paternal grandmother's maiden name?")], default='1', max_length=1)),
                ('mfa_login_mode', models.CharField(blank=True, default='', max_length=5, choices=[('', 'None'), ('EMAIL', 'Email'), ('SMS', 'Text Message (SMS)')], null=True)),
                ('mobile_phone_number', models.CharField(blank=True, help_text='US numbers only.', max_length=12)),
                ('remaining_user_invites', models.IntegerField(default=0)),
                ('authorize_applications', models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to authorize applications.')),
                ('aal', models.CharField(blank=True, choices=[('', 'Undefined'), ('0', 'AAL0'), ('1', 'AAL1'), ('2', 'AAL2'), ('3', 'AAL3')], default='1', help_text='See NIST SP 800 63 3 B for definitions.', max_length=1, verbose_name='Authenticator Assurance Level')),
                ('ial', models.CharField(blank=True, choices=[('', 'Undefined'), ('0', 'IAL0'), ('1', 'IAL1'), ('2', 'IAL2'), ('3', 'IAL3')], default='2', help_text='See NIST SP 800 63 3A for definitions.', max_length=1, verbose_name='Identity Assurance Level')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('sent', models.BooleanField(default=False, editable=False)),
                ('used', models.BooleanField(default=False)),
                ('resend', models.BooleanField(default=False, help_text='Check to resend')),
                ('added', models.DateField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valid', models.BooleanField(default=False)),
                ('user_id_hash', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('valid', models.BooleanField(default=True)),
                ('added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Developer Invitation',
            },
        ),
        migrations.CreateModel(
            name='EmailWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('details', models.TextField(blank=True, default='', max_length=2048)),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPasswordDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Descriptor Created On')),
                ('salt', models.CharField(editable=False, max_length=120, verbose_name='Salt')),
                ('iterations', models.IntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Iterations')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Descriptor',
                'verbose_name_plural': 'Password Descriptors',
                'ordering': ['-user', 'iterations'],
                'unique_together': {('user', 'iterations')},
            },
        ),
        migrations.CreateModel(
            name='PastPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(editable=False, max_length=255, verbose_name='Password Hash')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('userpassword_desc', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserPasswordDescriptor')),
            ],
            options={
                'verbose_name': 'Past Password',
                'verbose_name_plural': 'Past Passwords',
                'ordering': ['-userpassword_desc', 'password'],
                'unique_together': {('userpassword_desc', 'password', 'date_created')},
            },
        ),
        migrations.CreateModel(
            name='UserIdentificationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('weight', models.IntegerField(default=0, help_text='Integer value controlling the position of the label in lists.', verbose_name='List Weight')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
