# Generated by Django 2.2.24 on 2021-06-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0041_auto_20210324_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_login_mode',
        ),
        migrations.DeleteModel(
            name='EmailWebhook',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.RemoveField(
            model_name='mfacode',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestInvite',
        ),
        migrations.RemoveField(
            model_name='userregistercode',
            name='sender',
        ),
        migrations.DeleteModel(
            name='MFACode',
        ),
        migrations.DeleteModel(
            name='UserRegisterCode',
        ),
    ]
