# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_requestinvite_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
