# Generated by Django 2.2.28 on 2022-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210624_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationkey',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activationkey',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activationkey',
            name='key_status',
            field=models.CharField(blank=True, default='created', max_length=10),
        ),
    ]
