# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160713_1730'),
        ('accounts', '0003_auto_20160708_0420'),
    ]

    operations = [
    ]
