# Generated by Django 6.0.2 on 2026-03-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220706_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_answer_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_answer_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_answer_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
