# Generated by Django 6.0.2 on 2026-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('BEN', 'Beneficiary'), ('DEV', 'Developer'), ('ANB', 'Aligned Network Beneficiary')], default='DEV', max_length=5),
        ),
    ]
