# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge'),
        ('accounts', '0004_auto_20160720_1816'),
    ]

    operations = [
    ]
