# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_question_2',
            field=models.CharField(choices=[('1', 'What was the name of your best friend from childhood?'), ('2', 'What was the name of your elementary school?'), ('3', 'What was the name of your favorite pet?')], default='1', max_length=1),
        ),
    ]
