# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20160727_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFACode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[(b'', b'None'), (b'EMAIL', b'Email'), (b'SMS', b'Text Message (SMS)')], default=b'', max_length=5)),
                ('valid', models.BooleanField(default=True)),
                ('expires', models.DateTimeField(blank=True)),
                ('added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_login_mode',
            field=models.CharField(blank=True, choices=[(b'', b'None'), (b'EMAIL', b'Email'), (b'SMS', b'Text Message (SMS)')], default=b'', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, help_text='US numbers only.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_mfa_login',
            field=models.BooleanField(default=False),
        ),
    ]
