# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160811_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sms_mfa_login',
        ),
        migrations.AddField(
            model_name='mfacode',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='mfacode',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone_number',
            field=models.CharField(blank=True, help_text='US numbers only.', max_length=12),
        ),
    ]
