# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mfacode_tries_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfacode',
            name='mode',
            field=models.CharField(choices=[('', 'None'), ('EMAIL', 'Email'), ('SMS', 'Text Message (SMS)')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_login_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('EMAIL', 'Email'), ('SMS', 'Text Message (SMS)')], default='', max_length=5),
        ),
    ]
