# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_invitesavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user_type',
            field=models.CharField(choices=[('BEN', 'Beneficiary'), ('DEV', 'Developer')], default='BEN', max_length=5),
        ),
        migrations.AlterField(
            model_name='validpasswordresetkey',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
