# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161024_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinvite',
            name='organization',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
