# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20161102_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remaining_developer_invites',
        ),
    ]
