# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20161102_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregisterinvitation',
            old_name='first',
            new_name='first_name',
        ),
    ]
