# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20161102_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterinvitation',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userregisterinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Sender'),
        ),
    ]
