# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20161102_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterinvitation',
            name='user',
        ),
        migrations.AddField(
            model_name='userregisterinvitation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
