# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20161102_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterinvitation',
            name='resend',
            field=models.BooleanField(default=False, help_text=b'Check to resend'),
        ),
        migrations.AlterField(
            model_name='userregisterinvitation',
            name='sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
