# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20161111_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authorize_applications',
            field=models.BooleanField(default=False, help_text='Check this to allow the account to authorize applications.'),
        ),
    ]
