# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20161213_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='me_key',
            field=models.CharField(blank=True, default='', help_text="The user's lookup key", max_length=255),
        ),
    ]
