# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_userprofile_me_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='me_key',
        ),
    ]
