# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_emailwebhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestinvite',
            options={'verbose_name': 'Invite Request'},
        ),
    ]
