# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170519_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistercode',
            name='user_id_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
