# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userregistercode_user_id_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistercode',
            name='user_id_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
