# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20170818_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinvite',
            name='user_type',
            field=models.CharField(choices=[('BEN', 'Beneficiary'), ('DEV', 'Developer')], default='DEV', max_length=3),
        ),
    ]
