# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20171016_1542'),
        ('accounts', '0037_auto_20171014_0154'),
    ]

    operations = [
    ]
