# Generated by Django 2.1.10 on 2019-08-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20190528_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfacode',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestInvite',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_login_mode',
        ),
        migrations.DeleteModel(
            name='MFACode',
        ),
    ]
