# Generated by Django 2.1.10 on 2019-08-14 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20190528_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfacode',
            name='user',
            field=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.deletion.CASCADE, null=True)
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mfa_login_mode',
            field=models.CharField(
                blank=True,
                null=True,
                default="",
                max_length=5,
            ),
        ),
    ]
