# Generated by Django 2.2.17 on 2021-03-24 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20201028_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentificationlabel',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
