# Generated by Django 2.2.22 on 2021-06-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210324_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailWebhook',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.RemoveField(
            model_name='mfacode',
            name='user',
        ),
        migrations.DeleteModel(
            name='RequestInvite',
        ),
        migrations.RemoveField(
            model_name='userregistercode',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_login_mode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_key_reset',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box to issue a new access key. Doing so invalidates the existing key.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='authorize_applications',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to authorize applications.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_applications',
            field=models.BooleanField(blank=True, default=False, help_text='Check this to allow the account to register applications.'),
        ),
        migrations.DeleteModel(
            name='MFACode',
        ),
        migrations.DeleteModel(
            name='UserRegisterCode',
        ),
    ]
