version: '3.3'

services:

  bfddb:
    image: postgres:9.6
    environment:
      POSTGRES_DB: bfd
      POSTGRES_USER: bfd
      POSTGRES_PASSWORD: InsecureLocalDev
    ports:
      - "5433:5432"
  bfd:
    build:
      context: .
      dockerfile: Dockerfile
    user: dev
    working_dir: /code
    command: make docker
    volumes:
      - .:/code
      - ${BFD_DIR}:${BFD_MOUNT_POINT:-/app}
      - ${SYNTHETIC_DATA}:/synthetic-data
    environment:
      JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-amd64/"
      BFD_PORT: 9954
      LOCAL_SYNTHETIC_DATA: "/synthetic-data"
      BFD_MOUNT_POINT: ${BFD_MOUNT_POINT:-/app}
    ports:
      - "1337:9954"
      - "10999:10999"
    depends_on:
      - bfddb
  msls:
    build:
      context: ./msls
      dockerfile: Dockerfile
    command: msls
    ports: 
      - "8080:8080"
  bbdb:
    image: postgres
    environment:
      - POSTGRES_DB=bluebutton
      - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"
  bb20:
    build:
      context: ${BB20_CONTEXT}
      dockerfile: Dockerfile
    command: bash -c "if [ ! -d 'bluebutton-css' ] ; then git clone https://github.com/CMSgov/bluebutton-css.git ; else echo 'CSS already installed.' ; fi ; if [ '${BB20_ENABLE_REMOTE_DEBUG}' = true ] ; then python3 -m ptvsd --host 0.0.0.0 --port 5678 manage.py runserver 0.0.0.0:8000 --noreload ; else python3 manage.py runserver 0.0.0.0:8000; fi"
    environment:
      - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
      - DATABASES_CUSTOM=postgres://postgres:toor@bbdb:5432/bluebutton
      - OAUTHLIB_INSECURE_TRANSPORT=true
      - DJANGO_DEFAULT_SAMPLE_FHIR_ID="-20140000008325"
      - DJANGO_SECURE_SESSION=False
      - DJANGO_MEDICARE_LOGIN_URI=http://192.168.0.187:8080?scope=openid%20profile&client_id=bluebutton
      - DJANGO_SLS_USERINFO_ENDPOINT=http://msls:8080/userinfo
      - DJANGO_SLS_TOKEN_ENDPOINT=http://msls:8080/token
      - FHIR_URL=https://bfd.local:9954/v1/fhir/
      - BB20_ENABLE_REMOTE_DEBUG=${BB20_ENABLE_REMOTE_DEBUG}
      # - FHIR_URL="https://prod-sbx.bfdcloud.net/v1/fhir/"
      # - BB20_ENABLE_REMOTE_DEBUG=${BB20_ENABLE_REMOTE_DEBUG}
    ports:
      - "8000:8000"
      - "5678:5678"
    links:
      - "bfd:bfd.local"
    volumes:
      - ${BB20_CONTEXT}:/code
      - ./certstore:/certstore
    depends_on:
      - bbdb
      - msls
  bb20tests:
    build:
      context: ${BB20_CONTEXT}
      dockerfile: Dockerfile
    command: python3 -m ptvsd --host 0.0.0.0 --port 6789 --wait runtests.py
    environment:
      - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
      - DATABASES_CUSTOM=postgres://postgres:toor@bbdb:5432/bluebutton
      - OAUTHLIB_INSECURE_TRANSPORT=true
      - DJANGO_DEFAULT_SAMPLE_FHIR_ID="-20140000008325"
      - DJANGO_SECURE_SESSION=False
      - DJANGO_MEDICARE_LOGIN_URI=http://127.0.0.1:8080?scope=openid%20profile&client_id=bluebutton
      - DJANGO_SLS_USERINFO_ENDPOINT=http://msls:8080/userinfo
      - DJANGO_SLS_TOKEN_ENDPOINT=http://msls:8080/token
      - FHIR_URL=https://bfd.local:9954/v1/fhir/
    ports:
      - "6789:6789"
    volumes:
      - ${BB20_CONTEXT}:/code
      - ./certstore:/certstore
      