FROM python:3.14-trixie

ENV PYTHONUNBUFFERED=1
ENV PYDEVD_DISABLE_FILE_VALIDATION=1
ENV PYTHON_VERSION=3.14

# WARNING
# This is installing the most recent version of Postgres tools.
# We would rather install v16, to match the database, which matches Amazon.
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        ca-certificates \
        curl \ 
        gettext \
        gnupg \
        libffi-dev \
        libssl-dev \
        postgresql-client \
        python3-dev

# Set the local user for development
# and mount the codebase at /code
# Set this as the current/active path.
RUN useradd -m -s /bin/bash DEV
USER DEV
ADD .. /code
WORKDIR /code

RUN python -m venv /tmp/venv
RUN . /tmp/venv/bin/activate
ENV PATH="/tmp/venv/bin:${PATH}"
RUN pip install --upgrade pip pip-tools setuptools

# Trying to bring things through with vendor directory...
# RUN pip install --no-deps cffi --find-links /code/vendor/
# RUN pip install --no-deps markupsafe --find-links /code/vendor/
# RUN pip install --no-deps newrelic --find-links /code/vendor/

# THE NOW
# RUN pip install \
#     -r requirements/requirements.dev.txt \
#     --no-index \
#     --find-links /code/vendor/
# RUN pip install wheel setuptools pip --upgrade

# NEXT STEPS
# https://pip.pypa.io/en/stable/topics/secure-installs/
# https://www.b-list.org/weblog/2023/dec/07/pip-install-safely/
#
#     --only-binary :all:
# 
# does not work for some of our packages. Not all are available as .whl, and
# some are .tar.gz. We can *prefer* binary, but can't force it.
#
# We will iterate towards --only-binary.
RUN pip install \
    --require-hashes \
    --no-deps \
    --prefer-binary \
    -r requirements/requirements.dev.txt

