FROM python:3.12-trixie

ENV PYTHONUNBUFFERED=1
ENV PYDEVD_DISABLE_FILE_VALIDATION=1
ENV PYTHON_VERSION=3.12

# WARNING
# This is installing the most recent version of Postgres tools.
# We would rather install v16, to match the database, which matches Amazon.
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        ca-certificates \
        curl \ 
        gettext \
        gnupg \
        libffi-dev \
        libssl-dev \
        postgresql-client \
        python3-dev \
        socat

# Add in the codebase
ADD .. /code
WORKDIR /code

# This is a forward pointer to read-only images.
# We will want to install `nodejs` and `npm` via apt, and 
# use that to build our static assets into the container image.
# This will grow build time significantly, and is not included
# at this time. 
#
# Build the CSS/USWDS assets
# This builds them statically into the image, allowing us 
# to test a read-only configuration.
# RUN cd /code/static/bluebutton-css \
#     && npm i \
#     && npm run gulp

# Set the local user for development
# and mount the codebase at /code
# Set this as the current/active path.
RUN useradd -m -s /bin/bash DEV
# Make sure the DEV user can write to /media.
# Do this before the USER command.
RUN mkdir -p /media
RUN chown -R DEV:DEV /media
USER DEV

# Do the setup in a temporary venv
RUN python -m venv /tmp/venv
RUN . /tmp/venv/bin/activate
ENV PATH="/tmp/venv/bin:${PATH}"
RUN pip install --upgrade pip pip-tools setuptools

# NEXT STEPS
# https://pip.pypa.io/en/stable/topics/secure-installs/
# https://www.b-list.org/weblog/2023/dec/07/pip-install-safely/
#
#     --only-binary :all:
# 
# does not work for some of our packages. Not all are available as .whl, and
# some are .tar.gz. We can *prefer* binary, but can't force it.
#
# We will iterate towards --only-binary.
RUN pip install \
    --require-hashes \
    --no-deps \
    --prefer-binary \
    -r requirements/requirements.dev.txt

