repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.15.10
    hooks:
      # Run the linter
      - id: ruff-check
        exclude: 'migrations|docs|examples|vendor|venv|management|static'
      # Run the formatter
      - id: ruff-format
        exclude: 'migrations|docs|examples|vendor|venv|management|static'
