FROM selenium/standalone-chrome-debug

ENV PYTHONUNBUFFERED 1
USER root
RUN apt-get update && apt-get install -yq python3.7 python3-pip git
RUN pip3 install --upgrade pip
RUN pip3 install selenium psycopg2-binary==2.8.6 pyyaml==5.4.1 Pillow==9.0.0
RUN mkdir /code
ADD . /code/
WORKDIR /code
RUN make reqs-install-dev
RUN ln -s /usr/bin/python3 /usr/local/bin/python