# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  # selenium_tests:
  #   build:
  #     context: ./
  #     dockerfile: SeleniumDockerfile
  #   command: python3 runtests.py apps.integration_tests.auto_test_via_testclient.RunTestClient
  #   environment:
  #           - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
  #           - DATABASES_CUSTOM=postgres://postgres:toor@db:5432/bluebutton
  #           - OAUTHLIB_INSECURE_TRANSPORT=true
  #           - DJANGO_DEFAULT_SAMPLE_FHIR_ID="-20140000008325"
  #           - DJANGO_SECURE_SESSION=False
  #           - FHIR_URL="https://prod-sbx.bfd.cms.gov"
  #           - DJANGO_FHIR_CERTSTORE=/code/docker-compose/certstore/
  #           - DJANGO_MEDICARE_SLSX_LOGIN_URI=http://127.0.0.1:8080/sso/authorize?client_id=bb2api
  #           - DJANGO_MEDICARE_SLSX_REDIRECT_URI=http://localhost:8000/mymedicare/sls-callback
  #           - DJANGO_SLSX_USERINFO_ENDPOINT=http://msls:8080/v1/users
  #           - DJANGO_SLSX_HEALTH_CHECK_ENDPOINT=http://msls:8080/health
  #           - DJANGO_SLSX_TOKEN_ENDPOINT=http://msls:8080/sso/session
  #           - DJANGO_SLSX_SIGNOUT_ENDPOINT=http://msls:8080/sso/signout
  #           - DJANGO_SLSX_CLIENT_ID=bb2api
  #           - DJANGO_SLSX_CLIENT_SECRET=${DJANGO_SLSX_CLIENT_SECRET}
  #           # - DJANGO_MEDICARE_SLSX_LOGIN_URI=https://test.medicare.gov/sso/authorize?client_id=bb2api
  #           # - DJANGO_MEDICARE_SLSX_REDIRECT_URI=http://localhost:8000/mymedicare/sls-callback
  #           # - DJANGO_SLSX_HEALTH_CHECK_ENDPOINT=https://test.accounts.cms.gov/health
  #           # - DJANGO_SLSX_TOKEN_ENDPOINT=https://test.medicare.gov/sso/session
  #           # - DJANGO_SLSX_SIGNOUT_ENDPOINT=https://test.medicare.gov/sso/signout
  #           # - DJANGO_SLSX_USERINFO_ENDPOINT=https://test.accounts.cms.gov/v1/users
  #           - DJANGO_SLSX_VERIFY_SSL=False
  #           - DJANGO_LOG_JSON_FORMAT_PRETTY=True
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - web

  msls:
    build:
      context: ./dev-local/msls
      dockerfile: Dockerfile
    command: msls
    ports:
      - "8080:8080"

  db:
    image: postgres
    environment:
            - POSTGRES_DB=bluebutton
            - POSTGRES_PASSWORD=toor
    ports:
      - "5432:5432"

  web:
    build: 
      context: ./
      dockerfile: SeleniumDockerfile
    command: ./docker-compose/bluebutton_server_start.sh '${DB_MIGRATIONS}' '${SUPER_USER_NAME}' '${SUPER_USER_EMAIL}' '${SUPER_USER_PASSWORD}' '${BB20_ENABLE_REMOTE_DEBUG}' '${BB20_REMOTE_DEBUG_WAIT_ATTACH}'
    environment:
            - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
            - DATABASES_CUSTOM=postgres://postgres:toor@db:5432/bluebutton
            - OAUTHLIB_INSECURE_TRANSPORT=true
            - DJANGO_DEFAULT_SAMPLE_FHIR_ID="-20140000008325"
            - DJANGO_SECURE_SESSION=False
            - FHIR_URL="https://prod-sbx.bfd.cms.gov"
            - DJANGO_FHIR_CERTSTORE=/code/docker-compose/certstore/
            - DJANGO_MEDICARE_SLSX_LOGIN_URI=http://127.0.0.1:8080/sso/authorize?client_id=bb2api
            - DJANGO_MEDICARE_SLSX_REDIRECT_URI=http://localhost:8000/mymedicare/sls-callback
            - DJANGO_SLSX_USERINFO_ENDPOINT=http://msls:8080/v1/users
            - DJANGO_SLSX_HEALTH_CHECK_ENDPOINT=http://msls:8080/health
            - DJANGO_SLSX_TOKEN_ENDPOINT=http://msls:8080/sso/session
            - DJANGO_SLSX_SIGNOUT_ENDPOINT=http://msls:8080/sso/signout
            - DJANGO_SLSX_CLIENT_ID=bb2api
            - DJANGO_SLSX_CLIENT_SECRET=${DJANGO_SLSX_CLIENT_SECRET}
            # - DJANGO_MEDICARE_SLSX_LOGIN_URI=https://test.medicare.gov/sso/authorize?client_id=bb2api
            # - DJANGO_MEDICARE_SLSX_REDIRECT_URI=http://localhost:8000/mymedicare/sls-callback
            # - DJANGO_SLSX_HEALTH_CHECK_ENDPOINT=https://test.accounts.cms.gov/health
            # - DJANGO_SLSX_TOKEN_ENDPOINT=https://test.medicare.gov/sso/session
            # - DJANGO_SLSX_SIGNOUT_ENDPOINT=https://test.medicare.gov/sso/signout
            # - DJANGO_SLSX_USERINFO_ENDPOINT=https://test.accounts.cms.gov/v1/users
            - DJANGO_SLSX_VERIFY_SSL=False
            - DJANGO_LOG_JSON_FORMAT_PRETTY=True
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
      - msls
