version: '3'

services:
  tests:
    build:
      context: ./
      dockerfile: Dockerfile.selenium
    command: python runtests.py apps.integration_tests.selenium_tests.SeleniumTests
    environment:
          - HOSTNAME_URL=${HOSTNAME_URL}
          - USE_MSLSX=${USE_MSLSX}
          - USE_GRID=${USE_GRID}
    volumes:
      - .:/code
    depends_on:
      - bb2slsx
    profiles:
      - lite
    
  tests-grid:
    build:
      context: ./
      dockerfile: Dockerfile.selenium
    command: python runtests.py apps.integration_tests.selenium_tests.SeleniumTests
    environment:
          - HOSTNAME_URL=${HOSTNAME_URL}
          - USE_MSLSX=${USE_MSLSX}
          - USE_GRID=${USE_GRID}
    volumes:
      - .:/code
    depends_on:
      - bb2slsx
      - chrome
    profiles:
      - grid

  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210517
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    profiles:
      - grid
  
  # edge:
  #   image: selenium/node-edge:4.0.0-beta-4-prerelease-20210517
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6901:5900"
    
  # firefox:
  #   image: selenium/node-firefox:4.0.0-beta-4-prerelease-20210517
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   ports:
  #     - "6902:5900"
    
  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210517
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    profiles:
      - grid
    
  msls:
    build:
      context: ./dev-local/msls
      dockerfile: Dockerfile
    command: msls
    ports:
      - "8080:8080"
  
  db:
    image: postgres
    environment:
            - POSTGRES_DB=bluebutton
            - POSTGRES_PASSWORD=toor
    ports:
            - "5432:5432"

  bb2slsx:
    build: . 
    command: ./docker-compose/bluebutton_server_start.sh '${DB_MIGRATIONS}' '${SUPER_USER_NAME}' '${SUPER_USER_EMAIL}' '${SUPER_USER_PASSWORD}' '${BB20_ENABLE_REMOTE_DEBUG}' '${BB20_REMOTE_DEBUG_WAIT_ATTACH}'
    environment:
            - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
            - DATABASES_CUSTOM=postgres://postgres:toor@db:5432/bluebutton
            - OAUTHLIB_INSECURE_TRANSPORT=true
            - DJANGO_DEFAULT_SAMPLE_FHIR_ID="-20140000008325"
            - DJANGO_SECURE_SESSION=False
            - FHIR_URL="https://prod-sbx.bfd.cms.gov"
            - DJANGO_FHIR_CERTSTORE=${DJANGO_FHIR_CERTSTORE}
            - DJANGO_MEDICARE_SLSX_REDIRECT_URI=${DJANGO_MEDICARE_SLSX_REDIRECT_URI}
            - DJANGO_MEDICARE_SLSX_LOGIN_URI=${DJANGO_MEDICARE_SLSX_LOGIN_URI}
            - DJANGO_SLSX_HEALTH_CHECK_ENDPOINT=${DJANGO_SLSX_HEALTH_CHECK_ENDPOINT}
            - DJANGO_SLSX_TOKEN_ENDPOINT=${DJANGO_SLSX_TOKEN_ENDPOINT}
            - DJANGO_SLSX_SIGNOUT_ENDPOINT=${DJANGO_SLSX_SIGNOUT_ENDPOINT}
            - DJANGO_SLSX_USERINFO_ENDPOINT=${DJANGO_SLSX_USERINFO_ENDPOINT}
            - DJANGO_SLSX_CLIENT_ID=bb2api
            - DJANGO_SLSX_CLIENT_SECRET=${DJANGO_SLSX_CLIENT_SECRET}
            - HOSTNAME_URL=${HOSTNAME_URL}
            - DJANGO_SLSX_VERIFY_SSL_INTERNAL=False
            - DJANGO_SLSX_VERIFY_SSL_EXTERNAL=True
            - DJANGO_LOG_JSON_FORMAT_PRETTY=True
            - DJANGO_USER_ID_ITERATIONS=${DJANGO_USER_ID_ITERATIONS}
            - DJANGO_USER_ID_SALT=${DJANGO_USER_ID_SALT}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
      - msls
