# Exclude a variety of commonly ignored directories.
exclude = [
	"*/migrations/*",
	"docs",
	"examples",
	"static",
	"vendor",
	"venv",

  # TODO this file has what looks like some bugs, so I don't want to mess with it
  "apps/testclient/management/commands/create_test_users_and_applications_batch.py"
]

line-length = 120
indent-width = 4

# Python 3.12
target-version = "py312"

[lint]
# These are recommended by Ruff documentation: https://docs.astral.sh/ruff/linter/
# TODO: Consider adding more rulesets in the future.
select = [
          "E", # pycodestyle errors
          "F", # Pyflakes
          "W", # pycodestyle warnings
          "I", # isort
          "TID252", # no relative imports
          "RUF100", # unused-noqa
          ]
ignore = [
          "W191", # Tab indentation, handled by formatter
          "E111", # Indentation with invalid multiple, handled by formatter
          "E114", # Indentation with invalid multiple, in comments handled by formatter
          "E117", # Over-indented code, handled by formatter
          "E501" # Line too long, handled by formatter
          ]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# Do not automatically fix unsafe fixes
unfixable = []

[format]
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
