# Generated by Django 2.2.22 on 2021-05-13 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oauth2_provider.generators
import oauth2_provider.validators
import uuid


class Migration(migrations.Migration):

    replaces = [('dot_ext', '0001_initial'), ('dot_ext', '0002_auto_20160608_1524'), ('dot_ext', '0003_auto_20160720_1816'), ('dot_ext', '0003_auto_20160708_0420'), ('dot_ext', '0004_merge'), ('dot_ext', '0005_auto_20180122_1553'), ('dot_ext', '0006_django_cache'), ('dot_ext', '0007_auto_20180517_2051'), ('dot_ext', '0008_auto_20181101_2104'), ('dot_ext', '0009_auto_20181112_1856'), ('dot_ext', '0010_auto_20181219_2117'), ('dot_ext', '0011_auto_20181220_2037'), ('dot_ext', '0012_auto_20181220_2222'), ('dot_ext', '0013_auto_20181221_2114'), ('dot_ext', '0014_auto_20190117_1319'), ('dot_ext', '0014_auto_20190121_1345'), ('dot_ext', '0015_auto_20190131_1343'), ('dot_ext', '0016_auto_20190227_1737'), ('dot_ext', '0017_auto_20200806_1207'), ('dot_ext', '0018_auto_20200828_1820'), ('dot_ext', '0019_auto_20200902_2115'), ('dot_ext', '0020_auto_20200903_1419'), ('dot_ext', '0021_auto_20200918_1350'), ('dot_ext', '0022_auto_20200918_1802'), ('dot_ext', '0023_auto_20200923_1528'), ('dot_ext', '0024_auto_20210324_1543')]

    initial = True

    dependencies = [
        ('capabilities', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    run_before = [
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiresIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('expires_in', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=100, unique=True)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', validators=[oauth2_provider.validators.validate_uris])),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials')], max_length=32)),
                ('client_secret', models.CharField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skip_authorization', models.BooleanField(default=False)),
                ('agree', models.BooleanField(default=False)),
                ('scope', models.ManyToManyField(to='capabilities.ProtectedCapability', verbose_name='Scope *')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_application', to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('client_uri', models.CharField(blank=True, default='', help_text='This is typically a homepage for the application.', max_length=512, verbose_name='Client URI')),
                ('contacts', models.TextField(blank=True, default='', help_text='This is typically an email', max_length=512, verbose_name="Client's Contacts")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('logo_uri', models.CharField(blank=True, default='', max_length=512, verbose_name='Logo URI')),
                ('op_policy_uri', models.CharField(blank=True, default='', max_length=512)),
                ('op_tos_uri', models.CharField(blank=True, default='', max_length=512)),
                ('policy_uri', models.CharField(blank=True, default='', help_text='This can be a model privacy notice or other policy document.', max_length=512, verbose_name="Client's Policy URI")),
                ('software_id', models.CharField(blank=True, default='', help_text='A unique identifier for an application defined by its creator.', max_length=128)),
                ('tos_uri', models.CharField(blank=True, default='', max_length=512, verbose_name="Client's Terms of Service URI")),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunSQL(
            sql='CREATE TABLE "django_cache" (\n    "cache_key" varchar(255) NOT NULL PRIMARY KEY,\n    "value" text NOT NULL,\n    "expires" timestamp with time zone NOT NULL\n);\nCREATE INDEX "django_cache_expires" ON "django_cache" ("expires");\n',
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='first_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_tos_uri',
            field=models.CharField(blank=True, default='https://bluebutton.cms.gov/terms', max_length=512),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_uri',
            field=models.URLField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=512, null=True, verbose_name='Website URI'),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This is plain-text up to 1000 characters in length.', null=True, verbose_name='Application Description'),
        ),
        migrations.AddField(
            model_name='application',
            name='website_uri',
            field=models.URLField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=512, null=True, verbose_name='Website URI'),
        ),
        migrations.AddField(
            model_name='application',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='support_phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='ArchivedToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField(blank=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_archivedtoken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthFlowUuid',
            fields=[
                ('auth_uuid', models.UUIDField(primary_key=True, unique=True)),
                ('state', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('auth_pkce_method', models.CharField(max_length=16, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('auth_crosswalk_action', models.CharField(max_length=1, null=True)),
                ('auth_share_demographic_scopes', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='require_demographic_scopes',
            field=models.BooleanField(default=True, null=True, verbose_name='Are demographic scopes required?'),
        ),
        migrations.CreateModel(
            name='ApplicationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('applications', models.ManyToManyField(blank=True, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='client_uri',
            field=models.URLField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=512, null=True, verbose_name='Client URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Multiple redirect URIs can be separated by a space or on a separate line. Read more about implementing redirect URIs in our documentation.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(to='capabilities.ProtectedCapability'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
