# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='exp',
            field=models.DateTimeField(editable=False, verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='iat',
            field=models.DateTimeField(editable=False, verbose_name='Issued At'),
        ),
    ]
