# Generated by Django 2.2.24 on 2021-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0001_squashed_0025_auto_20210513_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFlowUuidCopy',
            fields=[
                ('auth_uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('auth_pkce_method', models.CharField(max_length=16, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('auth_crosswalk_action', models.CharField(max_length=1, null=True)),
                ('auth_share_demographic_scopes', models.BooleanField(null=True)),
            ],
        ),
    ]
