# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0002_auto_20160608_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
