# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0003_auto_20160708_0420'),
        ('dot_ext', '0003_auto_20160720_1816'),
    ]

    operations = [
    ]
