# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='endorsements',
        ),
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='client_uri',
            field=models.CharField(blank=True, default='', help_text='This is typically a homepage for the application.', max_length=512, verbose_name='Client URI'),
        ),
        migrations.AddField(
            model_name='application',
            name='contacts',
            field=models.TextField(blank=True, default='', help_text='This is typically an email', max_length=512, verbose_name="Client's Contacts"),
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='logo_uri',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Logo URI'),
        ),
        migrations.AddField(
            model_name='application',
            name='op_policy_uri',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='application',
            name='op_tos_uri',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='application',
            name='policy_uri',
            field=models.CharField(blank=True, default='', help_text='This can be a model privacy notice or other policy document.', max_length=512, verbose_name="Client's Policy URI"),
        ),
        migrations.AddField(
            model_name='application',
            name='software_id',
            field=models.CharField(blank=True, default='', help_text='A unique identifier for an application defined by its creator.', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='tos_uri',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name="Client's Terms of Service URI"),
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(to='capabilities.ProtectedCapability', verbose_name='Scope *'),
        ),
        migrations.DeleteModel(
            name='Endorsement',
        ),
    ]
