# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 18:46
from __future__ import unicode_literals

import apps.dot_ext.oauth2_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0005_auto_20180122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed URIs listed, space or new line separated. Including ??00000000:// for mobile native applications', validators=[apps.dot_ext.oauth2_validators.validate_uris]),
        ),
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(to='capabilities.ProtectedCapability'),
        ),
    ]
