# Generated by Django 3.2.20 on 2023-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0005_alter_application_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='application',
            name='data_access_type',
            field=models.CharField(choices=[('ONE_TIME', 'ONE_TIME - No refresh token needed.'), ('RESEARCH_STUDY', 'RESEARCH_STUDY - No expiration.'), ('THIRTEEN_MONTH', 'THIRTEEN_MONTH - Access expires in 13-months.')], default='ONE_TIME', max_length=16, null=True, verbose_name='Data Access Type:'),
        ),
    ]
