# Generated by Django 3.2.18 on 2023-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0005_alter_application_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_secret_plain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
