# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0005_auto_20180122_1553'),
    ]

    operations = [
        migrations.RunSQL("""CREATE TABLE "django_cache" (
    "cache_key" varchar(255) NOT NULL PRIMARY KEY,
    "value" text NOT NULL,
    "expires" timestamp with time zone NOT NULL
);
CREATE INDEX "django_cache_expires" ON "django_cache" ("expires");
"""),
    ]
