# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0006_expiresin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='iss',
            field=models.TextField(default='', help_text='Must contain a QDN', max_length=512, verbose_name='Issuer'),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='jws',
            field=models.TextField(default='', max_length=10240),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='title',
            field=models.TextField(default='', max_length=256),
        ),
    ]
