# Generated by Django 4.2.4 on 2023-10-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0006_alter_application_user_alter_archivedtoken_user_and_more'),
        ('dot_ext', '0006_auto_20230921_1021'),
    ]

    operations = [
    ]
