# Generated by Django 4.2.11 on 2024-07-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0007_merge_20231020_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='authflowuuid',
            name='auth_language',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='authflowuuidcopy',
            name='auth_language',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='data_access_type',
            field=models.CharField(choices=[('ONE_TIME', 'ONE_TIME - No refresh token needed.'), ('RESEARCH_STUDY', 'RESEARCH_STUDY - No expiration.'), ('THIRTEEN_MONTH', 'THIRTEEN_MONTH - Access expires in 13-months.')], default='THIRTEEN_MONTH', max_length=16, null=True, verbose_name='Data Access Type:'),
        ),
    ]
