# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0007_auto_20160513_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endorsement',
            old_name='jws',
            new_name='jwt',
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='iss',
            field=models.TextField(default='', help_text='Must contain a FQDN', max_length=512, verbose_name='Issuer'),
        ),
    ]
