# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0007_auto_20180517_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_tos_uri',
            field=models.CharField(blank=True, default='https://bluebutton.cms.gov/terms', max_length=512),
        ),
    ]
