# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0007_auto_20180517_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='first_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_tos_uri',
            field=models.CharField(blank=True, default='https://bluebutton.cms.gov/terms', max_length=512),
        ),
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed redirect URIs. Space or new line separated.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(to='capabilities.ProtectedCapability'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
