# Generated by Django 4.2.17 on 2025-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0008_internalapplicationlabels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalApplicationLabelsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Category',
                'verbose_name_plural': 'Internal Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.internalapplicationlabels',),
        ),
        migrations.AlterField(
            model_name='application',
            name='internal_application_labels',
            field=models.ManyToManyField(blank=True, to='dot_ext.internalapplicationlabels'),
        ),
    ]
