# Generated by Django 2.1.2 on 2018-12-19 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0009_auto_20181112_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='client_uri',
        ),
        migrations.AddField(
            model_name='application',
            name='website_uri',
            field=models.URLField(blank=True, default='', help_text='This is typically a home/download website for the application.', max_length=512, verbose_name='Website URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed redirect URIs. Space or new line separated.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(to='capabilities.ProtectedCapability'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
