# Generated by Django 6.0.2 on 2026-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0009_internalapplicationlabelsproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_client_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='jwks_uri',
            field=models.URLField(blank=True, default=None, max_length=512, null=True, verbose_name='JSON Web Key Set URI'),
        ),
    ]
