# Generated by Django 2.1.2 on 2019-01-15 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0009_auto_20181112_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_uri',
            field=models.CharField(blank=True, default='', help_text='This is typically a homepage for the application.', max_length=512, verbose_name='Client URI'),
        ),
    ]
