# Generated by Django 2.1.2 on 2018-12-20 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0010_auto_20181219_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This is a plain-text description of this application up to 1000 characters in length.', max_length=1000, verbose_name="Application's Description"),
        ),
    ]
