# Generated by Django 6.0.2 on 2026-05-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0011_remove_application_allow_client_credentials_and_more'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenExtension',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('include_samhsa', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('access_token', models.ForeignKey(db_column='access_token_id', on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken_extension',
            },
        ),
    ]
