# Generated by Django 2.1.2 on 2018-12-20 22:22

import apps.dot_ext.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0011_auto_20181220_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='', help_text='This is plain-text up to 1000 characters in length.', max_length=1000, validators=[apps.dot_ext.validators.validate_notags], verbose_name="Application's Description"),
        ),
    ]
