# Generated by Django 6.0.2 on 2026-04-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0011_remove_application_allow_client_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_uri',
            field=models.TextField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=512, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Client URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contacts',
            field=models.TextField(blank=True, default='', help_text='This is typically an email', verbose_name="Client's Contacts"),
        ),
        migrations.AlterField(
            model_name='application',
            name='jwks_uri',
            field=models.TextField(blank=True, default=None, max_length=512, null=True, validators=[django.core.validators.URLValidator()], verbose_name='JSON Web Key Set URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo_uri',
            field=models.TextField(blank=True, default='', max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='Logo URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_policy_uri',
            field=models.TextField(blank=True, default='', max_length=512, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_tos_uri',
            field=models.TextField(blank=True, default='https://bluebutton.cms.gov/terms', max_length=512, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='application',
            name='policy_uri',
            field=models.TextField(blank=True, default='', help_text='This can be a model privacy notice or other policy document.', max_length=512, validators=[django.core.validators.URLValidator()], verbose_name="Client's Policy URI"),
        ),
        migrations.AlterField(
            model_name='application',
            name='software_id',
            field=models.TextField(blank=True, default='', help_text='A unique identifier for an application defined by its creator.', max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='support_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='support_phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='tos_uri',
            field=models.TextField(blank=True, default='', max_length=512, validators=[django.core.validators.URLValidator()], verbose_name="Client's Terms of Service URI"),
        ),
        migrations.AlterField(
            model_name='application',
            name='website_uri',
            field=models.TextField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=512, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website URI'),
        ),
        migrations.AlterField(
            model_name='applicationlabel',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authflowuuid',
            name='state',
            field=models.TextField(db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internalapplicationlabels',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internalapplicationlabels',
            name='label',
            field=models.TextField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='internalapplicationlabels',
            name='slug',
            field=models.TextField(default='', max_length=1024, unique=True),
        ),
    ]
