# Generated by Django 6.0.2 on 2026-04-29 16:45

import apps.dot_ext.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0012_alter_protectedcapability_description'),
        ('dot_ext', '0011_remove_application_allow_client_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scope',
            field=models.ManyToManyField(default=apps.dot_ext.models.get_default_scopes, to='capabilities.protectedcapability'),
        ),
    ]
