# Generated by Django 6.0.2 on 2026-03-30 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0012_alter_protectedcapability_description'),
        ('dot_ext', '0011_remove_application_allow_client_credentials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='jwks_uri_required_for_client_credentials_or_both',
        ),
        migrations.AlterField(
            model_name='application',
            name='allowed_auth_type',
            field=models.CharField(choices=[('AUTH_CODE', 'AUTH_CODE - Can only authorize via grant_type = authorization_code'), ('CLIENT_CREDENTIALS', 'CLIENT_CREDENTIALS - Can only authorize with grant_type = client_credentials'), ('AUTH_CODE_AND_CLIENT_CREDS', 'AUTH_CODE_AND_CLIENT_CREDS - Can authorize with grant_type = authorization_code or client_credentials')], default='AUTH_CODE', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('allowed_auth_type', 'AUTH_CODE'), models.Q(('allowed_auth_type__in', ['CLIENT_CREDENTIALS', 'AUTH_CODE_AND_CLIENT_CREDS']), ('jwks_uri__isnull', False)), _connector='OR'), name='jwks_uri_required_for_client_credentials_or_both'),
        ),
    ]
