# Generated by Django 6.0.2 on 2026-05-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0012_accesstokenextension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpiresIn',
        ),
    ]
