# Generated by Django 6.0.2 on 2026-04-21 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0012_alter_application_client_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_uri',
            field=models.TextField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=2048, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Client URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='jwks_uri',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True, validators=[django.core.validators.URLValidator()], verbose_name='JSON Web Key Set URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo_uri',
            field=models.TextField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator()], verbose_name='Logo URI'),
        ),
        migrations.AlterField(
            model_name='application',
            name='policy_uri',
            field=models.TextField(blank=True, default='', help_text='This can be a model privacy notice or other policy document.', max_length=2048, validators=[django.core.validators.URLValidator()], verbose_name="Client's Policy URI"),
        ),
        migrations.AlterField(
            model_name='application',
            name='tos_uri',
            field=models.TextField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator()], verbose_name="Client's Terms of Service URI"),
        ),
        migrations.AlterField(
            model_name='application',
            name='website_uri',
            field=models.TextField(blank=True, default='', help_text='This is typically a home/download website for the application. For example, https://www.example.org or http://www.example.org .', max_length=2048, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website URI'),
        ),
    ]
