# Generated by Django 6.0.2 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0013_delete_expiresin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFlowTracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('include_samhsa', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'dot_ext_auth_flow_tracking',
            },
        ),
    ]
