# Generated by Django 6.0.2 on 2026-04-21 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0013_alter_application_client_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='op_policy_uri',
            field=models.TextField(blank=True, default='', max_length=2048, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='application',
            name='op_tos_uri',
            field=models.TextField(blank=True, default='https://bluebutton.cms.gov/terms', max_length=2048, validators=[django.core.validators.URLValidator()]),
        ),
    ]
