# Generated by Django 2.1.2 on 2019-01-22 17:01

import apps.dot_ext.models
import apps.dot_ext.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0013_auto_20181221_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload your logo image file here in JPEG (.jpg) format! The maximum file size allowed is 100KB and maximum dimensions are 128x128 pixels.', null=True, upload_to=apps.dot_ext.models.logo_image_filename, validators=[apps.dot_ext.validators.validate_logo_image], verbose_name='Logo Image Upload'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo_uri',
            field=models.CharField(blank=True, default='', help_text='This will be automatically updated via the Logo Image Upload after saving.', max_length=512, null=True, verbose_name='Logo URI'),
        ),
    ]
