# Generated by Django 6.0.2 on 2026-04-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0014_alter_application_op_policy_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='client_secret_plain',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
