# Generated by Django 6.0.2 on 2026-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0014_authflowtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokenextension',
            name='part_d_eob_only',
            field=models.BooleanField(default=False, verbose_name='Part D EOB Claims Only'),
        ),
        migrations.AddField(
            model_name='application',
            name='part_d_eob_only',
            field=models.BooleanField(default=False, verbose_name='Part D EOB Claims Only'),
        ),
    ]
