# Generated by Django 6.0.2 on 2026-04-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0015_alter_application_client_secret_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authflowuuid',
            name='client_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
