# Generated by Django 6.0.6 on 2026-08-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0015_accesstokenextension_part_d_eob_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authflowuuid',
            name='auth_share_samhsa_data',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='authflowuuidcopy',
            name='auth_share_samhsa_data',
            field=models.BooleanField(null=True),
        ),
    ]
