# Generated by Django 2.1.7 on 2019-02-27 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0015_auto_20190131_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtoken',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='archivedtoken',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dot_ext_archivedtoken', to=settings.AUTH_USER_MODEL),
        ),
    ]
