# Generated by Django 2.2.13 on 2020-07-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0016_auto_20190227_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='require_demographic_scopes',
            field=models.BooleanField(default=True, null=True, verbose_name='Are demographic scopes required?'),
        ),
    ]
