# Generated by Django 2.2.13 on 2020-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0016_auto_20190227_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFlowUuid',
            fields=[
                ('auth_uuid', models.UUIDField(primary_key=True, unique=True)),
                ('state', models.CharField(max_length=64, null=True, unique=True, db_index=True)),
                ('code', models.CharField(max_length=255, null=True, unique=True, db_index=True)),
            ],
        ),
    ]
