# Generated by Django 6.0.2 on 2026-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0016_alter_authflowuuid_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authflowuuid',
            name='auth_pkce_method',
            field=models.CharField(choices=[('S256', 'S256'), ('plain', 'plain')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='authflowuuidcopy',
            name='auth_pkce_method',
            field=models.CharField(choices=[('S256', 'S256'), ('plain', 'plain')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='authflowuuidcopy',
            name='client_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='authflowuuidcopy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='authflowuuidcopy',
            name='state',
            field=models.TextField(db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
