# Generated by Django 6.0.6 on 2026-08-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0016_authflowuuid_auth_share_samhsa_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthFlowTracking',
        ),
    ]
