# Generated by Django 2.2.13 on 2020-08-28 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0017_auto_20200806_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='authflowuuid',
            name='client_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
