# Generated by Django 2.2.13 on 2020-09-03 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0019_auto_20200902_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='authflowuuid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
