# Generated by Django 2.2.13 on 2020-09-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0020_auto_20200903_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='authflowuuid',
            name='auth_crosswalk_type',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
