# Generated by Django 2.2.13 on 2020-09-23 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0022_auto_20200918_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='require_demographic_scopes',
            field=models.BooleanField(default=True, null=True, verbose_name='Are demographic scopes required?'),
        ),
    ]
