# Generated by Django 2.2.17 on 2021-03-24 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0023_auto_20200923_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlabel',
            name='applications',
            field=models.ManyToManyField(blank=True, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
