# flake8: noqa

responses = {
    "success": {
        "status_code": 200,
        "content": {
            "resourceType":"Bundle",
            "id":"389a548b-9c85-4491-9795-9306a957030b",
            "meta":{
                "lastUpdated":"2019-12-18T13:40:02.792-05:00"
            },
            "type":"searchset",
            "total":1,
            "link":[
                {
                    "relation":"first",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"last",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"self",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/?_count=10&_format=application%2Fjson%2Bfhir&_id=-20000000002346&startIndex=0"
                }
            ],
            "entry":[
                {
                    "resource":{
                        "resourceType":"Patient",
                        "id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }
            ]
        },
    },
    "not_found": {
        "status_code": 200,
        "content": {
            "resourceType":"Bundle",
            "id":"389a548b-9c85-4491-9795-9306a957030b",
            "meta":{
                "lastUpdated":"2019-12-18T13:40:02.792-05:00"
            },
            "type":"searchset",
            "total":0,
            "link":[
                {
                    "relation":"first",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"last",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"self",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/?_count=10&_format=application%2Fjson%2Bfhir&_id=-20000000002346&startIndex=0"
                }
            ],
        },
    },
    "error": {
        "status_code": 500,
    },
    "duplicates": {
        "status_code": 200,
        "content": {
            "resourceType":"Bundle",
            "id":"389a548b-9c85-4491-9795-9306a957030b",
            "meta":{
                "lastUpdated":"2019-12-18T13:40:02.792-05:00"
            },
            "type":"searchset",
            "total":2,
            "link":[
                {
                    "relation":"first",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"last",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"self",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/?_count=10&_format=application%2Fjson%2Bfhir&_id=-20000000002346&startIndex=0"
                }
            ],
            "entry":[
                {
                    "resource":{
                        "resourceType":"Patient",
                        "id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }, {
                    "resource":{
                        "resourceType":"Patient",
                        "id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }
            ]
        },
    },
    "malformed": {
        "status_code": 200,
        "content": {
            "resourceType":"Bundle",
            "id":"389a548b-9c85-4491-9795-9306a957030b",
            "meta":{
                "lastUpdated":"2019-12-18T13:40:02.792-05:00"
            },
            "type":"searchset",
            "total":1,
            "link":[
                {
                    "relation":"first",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"last",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"self",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/?_count=10&_format=application%2Fjson%2Bfhir&_id=-20000000002346&startIndex=0"
                }
            ],
            "entry":[
                {
                    "resource":{
                        "resourceType":"Patient",
                        "_id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }
            ]
        },
    },
    "lying": {
        "status_code": 200,
        "content": {
            "resourceType":"Bundle",
            "id":"389a548b-9c85-4491-9795-9306a957030b",
            "meta":{
                "lastUpdated":"2019-12-18T13:40:02.792-05:00"
            },
            "type":"searchset",
            "total":1,
            "link":[
                {
                    "relation":"first",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"last",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient?_count=10&startIndex=0&_id=-20000000002346"
                },
                {
                    "relation":"self",
                    "url":"https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/?_count=10&_format=application%2Fjson%2Bfhir&_id=-20000000002346&startIndex=0"
                }
            ],
            "entry":[
                {
                    "resource":{
                        "resourceType":"Patient",
                        "id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }, {
                    "resource":{
                        "resourceType":"Patient",
                        "id":"-20000000002346",
                        "extension":[
                            {
                                "url":"https://bluebutton.cms.gov/resources/variables/race",
                                "valueCoding":{
                                    "system":"https://bluebutton.cms.gov/resources/variables/race",
                                    "code":"1",
                                    "display":"White"
                                }
                            }
                        ],
                        "identifier":[
                            {
                                "system":"https://bluebutton.cms.gov/resources/variables/bene_id",
                                "value":"-20000000002346"
                            },
                            {
                                "system":"https://bluebutton.cms.gov/resources/identifier/mbi-hash",
                                "value":"98765432137efea543f4f370f96f1dbf01c3e3129041dba3ea43675987654321"
                            }
                        ],
                        "name":[
                            {
                                "use":"usual",
                                "family":"Doe",
                                "given":[
                                    "John",
                                    "X"
                                ]
                            }
                        ],
                        "gender":"male",
                        "birthDate":"2000-06-01",
                        "address":[
                            {
                                "district":"999",
                                "state":"48",
                                "postalCode":"99999"
                            }
                        ]
                    }
                }
            ]
        },
    },
}
