#!/usr/bin/bash
#
# Script to copy folders generated by the convert_logs_from_splunk.py script to the S3 target folder for BFD-Insights
#
# This copies all "dt=*/" type folders from the current PWD directory to the target S3 folder.
#
# Provide S3 target path as the $1 command line arg. NOTE: Include the trailing "/" on the S3 path.
#
# Example:
#
# $ sh ../upload_folders_to_s3.sh s3://<S3 bucket>/databases/bb2/events-global-state-apps/
#
# NOTE: You must source the BFD AWS credentials in to your shell before running this!
#
for dir in $(ls -d dt\=*)
do
  echo "==="
  echo COPYING TO S3: ${dir}
  echo
  aws s3 cp "${dir}" "${1}${dir}" --recursive
  echo "==="
done
