FROM selenium/standalone-chromium

USER root

RUN apt-get update ; apt-get install -yq python3 python3-venv socat
RUN ln -s /usr/bin/python3 /usr/local/bin/python

# switch to existing seluser from selenium docker
USER seluser

ADD . /code
WORKDIR /code
RUN python -m venv /tmp/venv
RUN . /tmp/venv/bin/activate
ENV PATH="/tmp/venv/bin:${PATH}"

RUN pip3 install --upgrade pip
RUN pip3 install selenium pytest debugpy jsonschema python-dateutil
