# Generated by Django 2.2.13 on 2020-09-28 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bluebutton', '0005_auto_20200529_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryDashboard',
            fields=[
                ('crosswalk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bluebutton.Crosswalk')),
            ],
            bases=('bluebutton.crosswalk',),
        ),
    ]
