# Generated by Django 2.2.24 on 2021-07-02 17:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('bb2_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2User',
            fields=[
            ],
            options={
                'verbose_name': 'V2 User',
                'verbose_name_plural': 'V2 Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
