# Generated by Django 2.2.26 on 2022-02-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb2_tools', '0002_v2user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V2User',
        ),
    ]
