# Generated by Django 4.2.17 on 2024-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb2_tools', '0003_delete_v2user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticBeneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(db_column='fhir_id', db_index=True, default=None, max_length=80, unique=True)),
                ('mbi_unhashed', models.CharField(db_column='user_mbi', db_index=True, default=None, max_length=11, unique=True, verbose_name='HASH of User MBI ID')),
                ('medicaid_un', models.TextField()),
                ('medicaid_pw', models.TextField()),
                ('age', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('postal_code', models.TextField()),
                ('part_d_contract_number', models.TextField(blank=True, null=True)),
                ('carrier_claims_total', models.IntegerField(default=0)),
                ('dme_claims_total', models.IntegerField(default=0)),
                ('hha_claims_total', models.IntegerField(default=0)),
                ('hospice_claims_total', models.IntegerField(default=0)),
                ('inpatient_claims_total', models.IntegerField(default=0)),
                ('outpatient_claims_total', models.IntegerField(default=0)),
                ('snf_claims_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticBeneficiaryFilter',
            fields=[
            ],
            options={
                'verbose_name': 'Synthetic Beneficiary Filter',
                'verbose_name_plural': 'Synthetic Beneficiary Filters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bb2_tools.syntheticbeneficiary',),
        ),
    ]
