# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, default='', max_length=64)),
                ('session_key', models.CharField(db_index=True, default='', max_length=64)),
                ('next_uri', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
