# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-13 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicare_cb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonuserstate',
            name='session_key',
        ),
    ]
