# Generated by Django 5.2.9 on 2026-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicare_cb', '0001_squashed_0002_remove_anonuserstate_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuserstate',
            name='next_uri',
            field=models.TextField(default=''),
        ),
    ]
