# Generated by Django 6.0.2 on 2026-04-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicare_cb', '0003_alter_anonuserstate_next_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuserstate',
            name='next_uri',
            field=models.TextField(default='', max_length=512, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='anonuserstate',
            name='state',
            field=models.TextField(db_index=True, default='', max_length=64),
        ),
    ]
