# Generated by Django 6.0.2 on 2026-04-21 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymedicare_cb', '0004_alter_anonuserstate_next_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonuserstate',
            name='next_uri',
            field=models.TextField(default='', max_length=2048, validators=[django.core.validators.URLValidator()]),
        ),
    ]
