# Generated by Django 2.2.22 on 2021-05-13 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from oauth2_provider import settings as oauth2_settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth2_provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=oauth2_settings.GRANT_MODEL)),
                ('challenge', models.CharField(default=None, max_length=255)),
                ('challenge_method', models.CharField(default='S256', max_length=255)),
            ],
        ),
    ]
