# Generated by Django 2.2.22 on 2021-06-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallenge',
            name='challenge',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
