# Generated by Django 6.0.2 on 2026-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkce', '0001_squashed_0002_auto_20210513_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechallenge',
            name='challenge',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='codechallenge',
            name='challenge_method',
            field=models.CharField(choices=[('S256', 'S256'), ('plain', 'plain')], default='S256', max_length=5),
        ),
    ]
