export DJANGO_SETTINGS_MODULE=_start.settings.local
export DJANGO_DATABASE_ENGINE='django.db.backends.mysql'
export DJANGO_DATABASE_NAME='DATABASE_NAME'
export DJANGO_DATABASE_USER='USER_NAME'
export DJANGO_DATABASE_PASSWORD='USER_PASSWORD'
export DJANGO_DATABASE_HOST='DATABASE_HOST'
export DJANGO_DATABASE_PORT='3306'
