# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('slug', models.CharField(default='', max_length=100, unique=True, verbose_name='Scope')),
                ('protected_resources', models.TextField(default='[["GET", "/some-url"]]', help_text='A JSON list of pairs containing HTTP method and URL. It may contain [id] placeholders for wildcards\n                            Example: [["GET","/api/task1"], ["POST","/api/task2/[id]"]]\n                            ', max_length=10240)),
                ('description', models.TextField(blank=True, default='', max_length=10240)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Protected Capabilities',
                'verbose_name': 'Protected Capability',
            },
        ),
    ]
