# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
