# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_auto_20160613_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='protected_resources',
            field=models.TextField(default='[["GET", "/some-url"]]', help_text='A JSON list of pairs containing HTTP method and URL. It may contain [id] placeholders for wildcards\n                     Example: [["GET","/api/task1"], ["POST","/api/task2/[id]"]]', max_length=10240),
        ),
    ]
