# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0003_auto_20160621_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='protected_resources',
            field=models.TextField(default='[["GET", "/some-url"]]', help_text='A JSON list of pairs containing HTTP method and URL.\n        It may contain [id] placeholders for wildcards\n        Example: [["GET","/api/task1"], ["POST","/api/task2/[id]"]]', max_length=10240),
        ),
    ]
