# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0004_auto_20160216_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='protected_resources',
            field=models.TextField(default='[["GET", "/some-url"]]', help_text='A JSON list of pairs containing HTTP method and URL. It may contain [id] placeholders for wildcards\n                            Example: [["GET","/api/task1"], ["POST","/api/task2/[id]"]]\n                            ', max_length=10240),
        ),
        migrations.AlterField(
            model_name='protectedcapability',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Scope'),
        ),
    ]
