# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Scope'),
        ),
    ]
