# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-20 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('capabilities', '0006_auto_20170517_1350'),
        ('capabilities', '0006_auto_20170423_2201'),
    ]

    operations = [
    ]
