# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectedcapability',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
