# Generated by Django 6.0.2 on 2026-03-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0001_squashed_0010_auto_20190723_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='slug',
            field=models.TextField(default='', unique=True, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='protectedcapability',
            name='title',
            field=models.TextField(default='', unique=True),
        ),
    ]
