# Generated by Django 6.0.2 on 2026-03-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0011_alter_protectedcapability_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedcapability',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
