FROM --platform=linux/amd64 selenium/standalone-chromium

ENV PYTHONUNBUFFERED 1
USER root
RUN apt-get update ; apt-get install -yq python3 python3-venv
RUN ln -s /usr/bin/python3 /usr/local/bin/python

USER seluser
COPY requirements.dev.txt .
RUN python -m venv /tmp/venv
RUN . /tmp/venv/bin/activate
ENV PATH="/tmp/venv/bin:${PATH}"
RUN pip install --upgrade pip pip-tools setuptools
RUN pip install psycopg2-binary cffi
RUN pip install -r requirements.dev.txt
