module "platform" {
  source    = "../../modules/platform"
  providers = { aws = aws, aws.secondary = aws.secondary }

  app                 = local.app
  env                 = local.env
  service             = local.service
  root_module         = "https://github.com/CMSgov/bluebutton-web-server/tree/main/ops/services/${basename(abspath(path.module))}"
  ssm_hierarchy_roots = ["bb"]
}

data "aws_ssm_parameter" "bcda_account_id" {
  name = "/bb/${local.env}/app/sensitive/bcda_account_id"
}

data "aws_secretsmanager_secret_version" "datadog_cicd_api_key" {
  secret_id = "arn:aws:secretsmanager:${var.region}:${sensitive(data.aws_ssm_parameter.bcda_account_id.value)}:secret:/cdap/bb/${local.env}/datadog/cicd/api-key"
}

data "aws_secretsmanager_secret_version" "datadog_cicd_application_key" {
  secret_id = "arn:aws:secretsmanager:${var.region}:${sensitive(data.aws_ssm_parameter.bcda_account_id.value)}:secret:/cdap/bb/${local.env}/datadog/cicd/application-key"
}

locals {
  env     = terraform.workspace
  service = "monitors"

  default_tags = module.platform.default_tags

  ## Evaluates config/defaults.yml and overwrites values with those from config/${local.env}.yml for each
  ## variable/key type. Creates a hierarchy of defaults, so the modules/datadog_monitors defaults are
  ## the least prioritized, followed by config/defaults.yml, followed by the environment specific settings.

  defaults   = yamldecode(file("config/defaults.yml"))
  env_config = yamldecode(file("config/${local.env}.yml"))

  monitor_config = {
    for key in distinct(concat(keys(local.defaults), keys(local.env_config))) :
    key => try(
      # Attempt map merge (works if both values are map/object-typed)
      merge(
        lookup(local.defaults, key, {}),
        lookup(local.env_config, key, {})
      ),
      # Fallback to scalar: env wins, then default
      lookup(local.env_config, key, lookup(local.defaults, key, null))
    )
  }
}

module "common_datadog_monitors" {
  source = "github.com/CMSgov/cdap/terraform/modules/datadog_monitors?ref=d0f66be83b0cf14fd21e7795eff2ae31128621bf"

  app             = local.app
  env             = local.env
  monitor_config  = local.monitor_config
  custom_monitors = local.custom_monitors
}

locals {
  custom_monitors = [
    {
      name    = "[${upper(local.env)}] [${local.app}] ALB — Target Response Time High"
      type    = "metric alert"
      message = "ALB target has high average response time."
      query   = "avg(last_1h):avg:aws.applicationelb.target_response_time.average{application:${local.app}, environment:${local.env}} > ${local.env == "test" ? 1 : 0.35}"

      thresholds = {
        critical = local.env == "test" ? 1 : 0.35
        warning  = local.env == "test" ? 0.75 : 0.25
      }

      notify_no_data           = local.env != "test"
      no_data_timeframe_minute = 60

      require_full_window = false
    },
    {
      create = local.env != "test"

      name    = "[${upper(local.env)}] [${local.app}] ALB — Request Rate Low"
      type    = "metric alert"
      message = "Request rate / throughput is low."
      query   = "avg(last_1h):sum:aws.applicationelb.request_count{application:${local.app}, environment:${local.env}}.as_rate() < ${local.env == "prod" ? 0.1 : 0.001}"

      thresholds = {
        critical = local.env == "prod" ? 0.1 : 0.001
        warning  = local.env == "prod" ? 0.5 : 0.005
      }

      notify_no_data           = true
      no_data_timeframe_minute = 60

      require_full_window = false
    },
    {
      name    = "[${upper(local.env)}] [${local.app}] ALB — Maximum Unhealthy Hosts"
      type    = "metric alert"
      message = "Maximum number of unhealthy hosts passed threshold."
      query   = "max(last_1h):sum:aws.applicationelb.un_healthy_host_count.maximum{application:${local.app}, environment:${local.env}} >= 1"

      thresholds = {
        # TODO should this be 2 or something?
        critical = 1
        warning  = 0.5
      }

      notify_no_data           = true
      no_data_timeframe_minute = 60

      require_full_window = false
    },
    {
      name    = "[${upper(local.env)}] [${local.app}] ALB — Target 5xx Count High"
      type    = "metric alert"
      message = "High number of 5xx response codes generated by the target."
      query   = "sum(last_1h):sum:aws.applicationelb.httpcode_target_5xx{application:${local.app}, environment:${local.env}}.as_count() > 1000"

      thresholds = {
        critical = 1000
        warning  = 100
      }

      # TODO when editing this, why does the on_missing_data appear as "Show No data" even though that's not the default for counts?
      notify_no_data           = local.env != "test" # TODO should probably be false
      no_data_timeframe_minute = 60

      require_full_window = false
    },
    {
      name    = "[${upper(local.env)}] [${local.app}] APM — Error Rate High"
      type    = "metric alert"
      message = "Service ${local.app} has high error rate."
      # TODO what evaluation window?
      query = "sum(last_1h):sum:trace.django.request.errors{env:${local.env},service:${local.app},span.kind:server}.as_count() / sum:trace.django.request.hits{env:${local.env},service:${local.app},span.kind:server}.as_count() > 0.02"

      thresholds = {
        critical = 0.02
        warning  = 0.01
      }

      notify_no_data           = false
      no_data_timeframe_minute = 60

      require_full_window = false
    },
  ]
}
