---
draft_status: "published"
notifications:
  slack: true
  victorops: false
ecs:
  notify_no_data: false # test shuts down overnight
rds:
  notify_no_data: false # test shuts down overnight
  replica_lag_enabled: false # there are no replicas on test
