# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_consent',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='fhir_consent',
            name='revoked',
            field=models.DateTimeField(blank=True),
        ),
    ]
