# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_consent', '0002_auto_20161008_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhir_consent',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fhir_consent',
            name='revoked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
