# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_consent', '0003_auto_20161008_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_consent',
            name='key',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
