# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_consent', '0004_fhir_consent_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_consent',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
