# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_consent', '0005_fhir_consent_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhir_consent',
            name='state',
            field=models.CharField(blank=True, choices=[('0', 'REVOKED'), ('2', 'CREATED'), ('4', 'UPDATED')], default='2', max_length=1, null=True),
        ),
    ]
