services:
  ####################
  # Blue Button - Codebuild
  bb-api:
    image: bb-api:codebuild
    command: /home/boton/bb/ops/containers/bb-api/scripts/internal/entrypoint.bash
    env_file: ./files/external/.env.codebuild
    tmpfs:
      - /tmp:mode=1777,size=200m
    volumes:
      - ./bb-api/scripts:/home/boton/bb/ops/containers/bb-api/scripts
      - type: bind
        source: ../..
        target: /home/boton/bb