from django.urls import path
from .views import (
    authorize_link,
    authorize_link_v2,
    restart,
    callback,
    test_eob,
    test_eob_v2,
    test_userinfo,
    test_userinfo_v2,
    test_metadata,
    test_metadata_v2,
    test_openid_config,
    test_openid_config_v2,
    test_coverage,
    test_coverage_v2,
    test_patient,
    test_patient_v2,
    test_links,
    launch3rdapp,
    authorize,
)

urlpatterns = [
    path("authorize", authorize, name="testclient-authorize-4-3rdapp"),
    path("launch", launch3rdapp, name="testclient-launch-for-3rdapp"),
    path("restart", restart, name="testclient-restart-for-3rdapp"),
    path("callback", callback, name="testclient-callback-for-3rdapp"),
    path("authorize-link", authorize_link, name="authorize_link-for-3rdapp"),
    path("authorize-link-v2", authorize_link_v2, name="authorize_link_v2-for-3rdapp"),
    path("", test_links, name="test_links-for-3rdapp"),
    path("ExplanationOfBenefit", test_eob, name="test_eob-for-3rdapp"),
    path("Patient", test_patient, name="test_patient-for-3rdapp"),
    path("Coverage", test_coverage, name="test_coverage-for-3rdapp"),
    path("userinfo", test_userinfo, name="test_userinfo-for-3rdapp"),
    path("metadata", test_metadata, name="test_metadata-for-3rdapp"),
    path("openidConfig", test_openid_config, name="test_openid_config-for-3rdapp"),
    path("ExplanationOfBenefitV2", test_eob_v2, name="test_eob_v2-for-3rdapp"),
    path("PatientV2", test_patient_v2, name="test_patient_v2-for-3rdapp"),
    path("CoverageV2", test_coverage_v2, name="test_coverage_v2-for-3rdapp"),
    path("userinfoV2", test_userinfo_v2, name="test_userinfo_v2-for-3rdapp"),
    path("metadataV2", test_metadata_v2, name="test_metadata_v2-for-3rdapp"),
    path("openidConfigV2", test_openid_config_v2, name="test_openid_config_v2-for-3rdapp"),
]
