from django.urls import path
from .views import (
    authorize_link,
    authorize_link_v2,
    restart,
    callback,
    test_eob,
    test_eob_v2,
    test_userinfo,
    test_userinfo_v2,
    test_metadata,
    test_metadata_v2,
    test_openid_config,
    test_openid_config_v2,
    test_coverage,
    test_coverage_v2,
    test_patient,
    test_patient_v2,
    test_links,
    test_claim,
    test_claimresponse,
)

urlpatterns = [
    path("restart", restart, name="testclient-restart"),
    path("callback", callback, name="testclient-callback"),
    path("authorize-link", authorize_link, name="authorize_link"),
    path("authorize-link-v2", authorize_link_v2, name="authorize_link_v2"),
    path("", test_links, name="test_links"),
    path("ExplanationOfBenefit", test_eob, name="test_eob"),
    path("Patient", test_patient, name="test_patient"),
    path("Coverage", test_coverage, name="test_coverage"),
    path("userinfo", test_userinfo, name="test_userinfo"),
    path("metadata", test_metadata, name="test_metadata"),
    path("openidConfig", test_openid_config, name="test_openid_config"),
    path("ExplanationOfBenefitV2", test_eob_v2, name="test_eob_v2"),
    path("PatientV2", test_patient_v2, name="test_patient_v2"),
    path("CoverageV2", test_coverage_v2, name="test_coverage_v2"),
    path("userinfoV2", test_userinfo_v2, name="test_userinfo_v2"),
    path("ClaimV2", test_claim, name="test_claim"),
    path("ClaimResponseV2", test_claimresponse, name="test_claimresponse"),
    path("metadataV2", test_metadata_v2, name="test_metadata_v2"),
    path("openidConfigV2", test_openid_config_v2, name="test_openid_config_v2"),
]
