openapi: 3.0.2
info:
  title: BlueButton 2.0
  version: 1.0.0
  description: "In order to try out the API you'll first need to get an access token and use it in the Authorize -> bearerAuth setting. To get one you can use the [test client](https://sandbox.bluebutton.cms.gov/testclient/), [postman](https://bluebutton.cms.gov/developers/#try-the-api), or your own local setup. The metadata endpoint is unprotected so you can use it without an access code. The metadata results will tell you what query parameters are available for the different fhir endpoints." 
paths:
  /.well-known/openid-configuration:
    get:
      operationId: openIdConfig
      description: ''
      security: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /v1/fhir/metadata:
    get:
      operationId: fhirMetaData
      description: ''
      security: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /v1/connect/userinfo:
    get:
      operationId: listopenidconnect_userinfos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  '/v1/fhir/Patient/{resource_id}':
    get:
      operationId: listReadViewPatients
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /v1/fhir/Patient/:
    get:
      operationId: listSearchViewPatients
      description: ''
      parameters:
        - in: query
          name: identifier
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
        - in: query
          name: _has:Coverage
          schema:
            type: string
          required: false
          description: 'Part D coverage type/year'
        - in: query
          name: cursor
          schema:
            type: string
          required: false
          description: 'The cursor used for result pagination'
        - in: query
          name: _id
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  '/v1/fhir/Coverage/{resource_id}':
    get:
      operationId: listReadViewCoverages
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /v1/fhir/Coverage/:
    get:
      operationId: listSearchViewCoverages
      description: ''
      parameters:
        - in: query
          name: beneficiary
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  '/v1/fhir/ExplanationOfBenefit/{resource_id}':
    get:
      operationId: listReadViewExplanationOfBenefits
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /v1/fhir/ExplanationOfBenefit/:
    get:
      operationId: listSearchViewExplanationOfBenefits
      description: ''
      parameters:
        - in: query
          name: patient
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: excludeSAMHSA
          schema:
            type: string
          required: false
          description: 'If true, exclude all SAMHSA-related resources'
        - in: query
          name: service-date
          schema:
            type: string
          required: false
          description: 'Include resources that completed in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
        - in: query
          name: type
          schema:
            type: string
          required: false
          description: 'A list of claim types to include'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v1
  /.well-known/openid-configuration-v2:
    get:
      operationId: openIdConfig_v2
      description: ''
      security: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  /v2/fhir/metadata:
    get:
      operationId: fhirMetaData_v2
      description: ''
      security: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  /v2/connect/userinfo:
    get:
      operationId: listopenidconnect_userinfos_v2
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  '/v2/fhir/Patient/{resource_id}':
    get:
      operationId: listReadViewPatients_v2
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  /v2/fhir/Patient/:
    get:
      operationId: listSearchViewPatients_v2
      description: ''
      parameters:
        - in: query
          name: identifier
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
        - in: query
          name: _has:Coverage
          schema:
            type: string
          required: false
          description: 'Part D coverage type/year'
        - in: query
          name: cursor
          schema:
            type: string
          required: false
          description: 'The cursor used for result pagination'
        - in: query
          name: _id
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  '/v2/fhir/Coverage/{resource_id}':
    get:
      operationId: listReadViewCoverages_v2
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  /v2/fhir/Coverage/:
    get:
      operationId: listSearchViewCoverages_v2
      description: ''
      parameters:
        - in: query
          name: beneficiary
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  '/v2/fhir/ExplanationOfBenefit/{resource_id}':
    get:
      operationId: listReadViewExplanationOfBenefits_v2
      description: ''
      parameters:
        - name: resource_id
          in: path
          required: true
          description: ''
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
  /v2/fhir/ExplanationOfBenefit/:
    get:
      operationId: listSearchViewExplanationOfBenefits_v2
      description: ''
      parameters:
        - in: query
          name: patient
          schema:
            type: string
          required: false
          description: 'The patient identifier to search for'
        - in: query
          name: _lastUpdated
          schema:
            type: string
          required: false
          description: 'Include resources last updated in the given range'
        - in: query
          name: excludeSAMHSA
          schema:
            type: string
          required: false
          description: 'If true, exclude all SAMHSA-related resources'
        - in: query
          name: service-date
          schema:
            type: string
          required: false
          description: 'Include resources that completed in the given range'
        - in: query
          name: startIndex
          schema:
            type: string
          required: false
          description: 'The offset used for result pagination'
        - in: query
          name: type
          schema:
            type: string
          required: false
          description: 'A list of claim types to include'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
            application/fhir+json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
        - v2
components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
          
  schemas: {}
servers:
  - url: 'https://sandbox.bluebutton.cms.gov/'
  - url: 'https://test.bluebutton.cms.gov/'
  - url: 'http://localhost:8000/'
    variables: {}
security:
    - bearerAuth: []
