services:
  ####################
  # Selenium Tests - Codebuild
  selenium-tests:
    image: selenium-local:latest
    command: /code/ops/containers/selenium/start-selenium-codebuild.sh
    network_mode: "host"
    environment:
      - HOSTNAME_URL=http://localhost:8000
      - USE_MSLSX=false
      - USE_LOGIN_WITH_MEDICARE_BUTTON=true
      - USE_NEW_PERM_SCREEN=true
      - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.test
      - SELENIUM_GRID=true
      - SELENIUM_GRID_HOST=localhost
      - DEBUG_MODE=false
      - TARGET_ENV=codebuild
      - PYTEST_SHOW_TRACE_OPT=
    volumes:
      - type: bind
        source: ../..
        target: /code

  ####################
  # Chrome for Selenium Remote
  chrome:
    image: selenium/standalone-chromium
    hostname: chrome
    network_mode: "host"
