services:
  ####################
  # Blue Button
  bb-api:
    image: bb-api:codebuild
    command: /home/boton/bb/ops/containers/bb-api/scripts/internal/entrypoint.bash
    env_file: ./bb-api/files/external/.env.codebuild
    volumes:
      - ./bb-api/scripts:/home/boton/bb/ops/containers/bb-api/scripts
      - type: bind
        source: ../..
        target: /home/boton/bb
        read_only: ${READ_ONLY:-true}
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 200000000 # 200MB
          mode: 1777