from django.test import TestCase
from django.urls.base import reverse

test_uuid = "0123456789abcdefghijklmnopqrstuvwxyz"
test_username = "0123456789abcdefghijklmnopqrstuvwxyz"

EXPECTED = {
    'oauth2_provider:authorize': '/v1/o/authorize/',
    'oauth2_provider:authorized-token-list': '/v1/o/authorized_tokens/',
    'oauth2_provider_v2:authorized-token-list-v2': '/v2/o/authorized_tokens/',
    'oauth2_provider:authorize-instance': '/v1/o/authorize/0123456789abcdefghijklmnopqrstuvwxyz/',
    'oauth2_provider_v2:authorize-instance-v2': '/v2/o/authorize/0123456789abcdefghijklmnopqrstuvwxyz/',
    'oauth2_provider_v2:authorize-v2': '/v2/o/authorize/',
    'oauth2_provider:delete': '/v1/o/applications/1234567890/delete/',
    'oauth2_provider_v2:delete-v2': '/v2/o/applications/1234567890/delete/',
    'oauth2_provider:detail': '/v1/o/applications/1234567890/',
    'oauth2_provider_v2:detail-v2': '/v2/o/applications/1234567890/',
    'oauth2_provider:introspect': '/v1/o/introspect/',
    'oauth2_provider_v2:introspect-v2': '/v2/o/introspect/',
    'oauth2_provider:list': '/v1/o/applications/',
    'oauth2_provider_v2:list-v2': '/v2/o/applications/',
    'oauth2_provider:register': '/v1/o/applications/register/',
    'oauth2_provider_v2:register-v2': '/v2/o/applications/register/',
    'oauth2_provider:revoke-token': '/v1/o/revoke_token/',
    'oauth2_provider_v2:revoke-token-v2': '/v2/o/revoke_token/',
    'oauth2_provider:token': '/v1/o/token/',
    'oauth2_provider_v2:token-v2': '/v2/o/token/',
    'oauth2_provider:update': '/v1/o/applications/1234567890/update/',
    'oauth2_provider_v2:update-v2': '/v2/o/applications/1234567890/update/',
    'account_settings': '/v1/accounts/settings',
    'account_settings_v2': '/v2/accounts/settings',
    'applications': '/admin/metrics/applications/',
    'applications-detail': '/admin/metrics/applications/1234567890',
    'archived-tokens': '/admin/metrics/tokens/archive',
    'archive-grants': '/admin/metrics/grants/archive',
    'authorize_link': '/testclient/authorize-link',
    'authorize_link_v2': '/testclient/authorize-link-v2',
    'beneficiaries': '/admin/metrics/beneficiaries',
    'check-crosswalks': '/admin/metrics/crosswalks/check',
    'check-grants': '/admin/metrics/grants/check',
    'developers': '/admin/metrics/developers/',
    'fhir_conformance_metadata': '/v1/fhir/metadata',
    'fhir_conformance_metadata_v2': '/v2/fhir/metadata',
    'grants': '/admin/metrics/grants',
    'home': '/home',
    'login': '/v1/accounts/login',
    'login_v2': '/v2/accounts/login',
    'logout': '/v1/accounts/logout',
    'logout_v2': '/v2/accounts/logout',
    'my_profile': '/v1/accounts/api/profile',
    'my_profile_v2': '/v2/accounts/api/profile',
    'mymedicare-login': '/mymedicare/login',
    'mymedicare-login-v2': '/mymedicare/login-v2',
    'mymedicare-sls-callback': '/mymedicare/sls-callback',
    'mymedicare-sls-callback-v2': '/mymedicare/sls-callback-v2',
    'openid_connect_userinfo': '/v1/connect/userinfo',
    'openid_connect_userinfo_v2': '/v2/connect/userinfo',
    'test_coverage': '/testclient/Coverage',
    'test_eob': '/testclient/ExplanationOfBenefit',
    'test_links': '/testclient/',
    'test_patient': '/testclient/Patient',
    'test_userinfo': '/testclient/userinfo',
    'testclient-callback': '/testclient/callback',
    'testclient-callback-v2': '/testclient/callback-v2',
    'tokens': '/admin/metrics/tokens',
    'unauth_home': '/',
}

URLS_NAMES = {
    "oauth2_provider:authorize": None,
    "oauth2_provider:authorized-token-list": None,
    "oauth2_provider_v2:authorized-token-list-v2": None,
    "oauth2_provider:authorize-instance": test_uuid,
    "oauth2_provider_v2:authorize-instance-v2": test_uuid,
    "oauth2_provider_v2:authorize-v2": None,
    "oauth2_provider:delete": 1234567890,
    "oauth2_provider_v2:delete-v2": 1234567890,
    "oauth2_provider:detail": 1234567890,
    "oauth2_provider_v2:detail-v2": 1234567890,
    "oauth2_provider:introspect": None,
    "oauth2_provider_v2:introspect-v2": None,
    "oauth2_provider:list": None,
    "oauth2_provider_v2:list-v2": None,
    "oauth2_provider:register": None,
    "oauth2_provider_v2:register-v2": None,
    "oauth2_provider:revoke-token": None,
    "oauth2_provider_v2:revoke-token-v2": None,
    "oauth2_provider:token": None,
    "oauth2_provider_v2:token-v2": None,
    "oauth2_provider:update": 1234567890,
    "oauth2_provider_v2:update-v2": 1234567890,
    "account_settings": None,
    "account_settings_v2": None,
    "applications": None,
    "applications-detail": 1234567890,
    "archived-tokens": None,
    "archive-grants": None,
    "authorize_link": None,
    "authorize_link_v2": None,
    "beneficiaries": None,
    "check-crosswalks": None,
    "check-grants": None,
    "developers": None,
    "fhir_conformance_metadata": None,
    "fhir_conformance_metadata_v2": None,
    "grants": None,
    "home": None,
    "login": None,
    "login_v2": None,
    "logout": None,
    "logout_v2": None,
    "my_profile": None,
    "my_profile_v2": None,
    "mymedicare-login": None,
    "mymedicare-login-v2": None,
    "mymedicare-sls-callback": None,
    "mymedicare-sls-callback-v2": None,
    "openid_connect_userinfo": None,
    "openid_connect_userinfo_v2": None,
    "test_coverage": None,
    "test_eob": None,
    "test_links": None,
    "test_patient": None,
    "test_userinfo": None,
    "testclient-callback": None,
    "testclient-callback-v2": None,
    "tokens": None,
    "unauth_home": None,
}


class URLSReverseTest(TestCase):
    def test_reverse_urls(self):
        for k, v in URLS_NAMES.items():
            uri = reverse(k, args=[v]) if v is not None else reverse(k)
            self.assertEqual(uri, EXPECTED[k])
