#!groovy
def aws_creds = 'cbj-deploy'

pipeline {
  agent any

  stages {
    stage('Clear') {
      steps {
        deleteDir()
      }
    }

    stage('Checkout') {
      steps {
        checkout([
            $class: 'GitSCM',
            branches: [[name: "${params.GIT_VERSION}"]],
            userRemoteConfigs: [[
              url: 'https://github.com/CMSgov/bluebutton-css.git'
            ]]
        ])
      }
    }

    stage('Deploy to Test') {
      steps {
        withAwsCli(credentialsId: aws_creds, defaultRegion: 'us-east-1') {
          sh """
            aws s3 sync ./dist/* s3://test.bluebutton.cms.gov/assets/css
          """
        }
      }
    }
  }
}
