# Generated by Django 2.2.22 on 2021-05-13 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bluebutton', '0001_initial'), ('bluebutton', '0002_auto_20180127_2032'), ('bluebutton', '0003_auto_20191208_0010'), ('bluebutton', '0004_auto_20191220_2327'), ('bluebutton', '0005_auto_20200529_1906')]

    initial = True

    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dot_ext', '0001_squashed_0025_auto_20210513_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fhir_id', models.CharField(db_column='fhir_id', db_index=True, default=None, max_length=80, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_id_type', models.CharField(choices=[('H', 'HICN'), ('M', 'MBI')], default='H', max_length=1, verbose_name='Hash ID type last used for FHIR_ID lookup')),
                ('_user_id_hash', models.CharField(db_column='user_id_hash', db_index=True, default=None, max_length=64, unique=True, verbose_name='HASH of User HICN ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('_user_mbi_hash', models.CharField(db_column='user_mbi_hash', db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='HASH of User MBI ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyAccessToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oauth2_provider.accesstoken',),
        ),
        migrations.CreateModel(
            name='MyApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.application',),
        ),
        migrations.CreateModel(
            name='MyAuthFlowUuid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.authflowuuid',),
        ),
    ]
