# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0015_resourcerouter_supported_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueButtonText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_content', models.TextField(blank=True, help_text='The MyMedicare.gov Blue Button text file is stored here.', null=True, verbose_name='Blue Button Text File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, default='', max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('mb_user', models.CharField(blank=True, default='', max_length=250)),
                ('user_id_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash of User ID')),
                ('beneid', models.CharField(blank=True, default='', max_length=11, verbose_name='Beneficiary Id')),
                ('fhir_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ResourceRouter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
