# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FhirServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Friendly Server Name')),
                ('fhir_url', models.URLField(verbose_name='Full URL to FHIR API with terminating /')),
                ('shard_by', models.CharField(default='Patient', max_length=80, verbose_name='Key Resource type')),
            ],
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='fhir_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluebutton.FhirServer'),
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
