# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crosswalk',
            old_name='fhir_source',
            new_name='fhir_src',
        ),
    ]
