# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user_id_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='PBKDF2 of User ID'),
        ),
    ]
