# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosswalk',
            name='beneid',
        ),
        migrations.RemoveField(
            model_name='crosswalk',
            name='mb_user',
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='user_id_type',
            field=models.CharField(choices=[('H', 'HICN'), ('M', 'MBI'), ('S', 'SSN')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user_id_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='PBKDF2 of User ID'),
        ),
    ]
