# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetypecontrol',
            name='search_add',
            field=models.TextField(blank=True, default='', help_text='list of keys that need to be added to search parameters to filter\n        information that is returned. eg. eg. Patient=%PATIENT%', max_length=200),
        ),
    ]
