# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0002_auto_20170925_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
