# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0002_auto_20160621_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetypecontrol',
            name='default_url',
            field=models.URLField(blank=True, help_text='Exclude the resource. eg. <b>https://fhirserver.com/fhir/Patient/</b> is entered as <b>https://fhirserver.com/fhir/</b></br>Leave blank to accept system default.', verbose_name='Default FHIR URL with terminating /'),
        ),
        migrations.AlterField(
            model_name='resourcetypecontrol',
            name='search_add',
            field=models.TextField(blank=True, default='', help_text='list of keys that need to be added to search parameters to filter information that is returned. eg. <b>Patient=%PATIENT%</b>', max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcetypecontrol',
            name='search_block',
            field=models.TextField(blank=True, default='', help_text='list of values that need to be removed from search parameters. eg. <b>Patient</b>', max_length=5120),
        ),
    ]
