# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0002_auto_20171012_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosswalk',
            name='fhir_src',
        ),
    ]
