# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_resourcerouter_wait_time'),
        ('bluebutton', '0003_remove_crosswalk_fhir_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='fhir_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.ResourceRouter'),
        ),
    ]
