# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0003_auto_20160621_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='mb_user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
