# Generated by Django 2.2.24 on 2021-12-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_ext', '0002_authflowuuidcopy'),
        ('creds', '0001_initial'),
        ('bluebutton', '0003_archivedcrosswalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.application',),
        ),
        migrations.CreateModel(
            name='MyCredentialingRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('creds.credentialingreqest',),
        ),
    ]
