# Generated by Django 4.2.17 on 2025-02-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0004_createnewapplication_mycredentialingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='_user_mbi',
            field=models.CharField(db_column='user_mbi', db_index=True, default=None, max_length=32, null=True, unique=True, verbose_name='User MBI ID'),
        ),
    ]
