# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0004_crosswalk_fhir_source'),
        ('bluebutton', '0004_auto_20171016_1544'),
    ]

    operations = [
    ]
