# Generated by Django 2.2.12 on 2020-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0004_auto_20191220_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='_user_mbi_hash',
            field=models.CharField(db_column='user_mbi_hash', db_index=True, default=None, max_length=64, null=True, unique=True, verbose_name='HASH of User MBI ID'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='_user_id_hash',
            field=models.CharField(db_column='user_id_hash', db_index=True, default=None, max_length=64, unique=True, verbose_name='HASH of User HICN ID'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user_id_type',
            field=models.CharField(choices=[('H', 'HICN'), ('M', 'MBI')], default='H', max_length=1, verbose_name='Hash ID type last used for FHIR_ID lookup'),
        ),
    ]
