# Generated by Django 4.2.20 on 2025-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0004_createnewapplication_mycredentialingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='_user_mbi',
            field=models.CharField(db_index=True, default=None, max_length=11, null=True, verbose_name='Unhashed MBI'),
        ),
    ]
