# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0005_auto_20160701_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_source',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='bluebutton.FhirServer'),
        ),
    ]
