# Generated by Django 2.2.22 on 2021-05-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
        ('dot_ext', '0025_auto_20210513_1812'),
        ('bluebutton', '0005_auto_20200529_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccessToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('oauth2_provider.accesstoken',),
        ),
        migrations.CreateModel(
            name='MyApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.application',),
        ),
        migrations.CreateModel(
            name='MyAuthFlowUuid',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dot_ext.authflowuuid',),
        ),
        migrations.RemoveField(
            model_name='crosswalk',
            name='fhir_source',
        ),
    ]
