# Generated by Django 4.2.20 on 2025-07-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0005_crosswalk__user_mbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='_user_mbi',
            field=models.CharField(db_column='user_mbi', db_index=True, default=None, max_length=11, null=True, verbose_name='Unhashed MBI'),
        ),
    ]
