# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluebuttontext',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlueButtonText',
        ),
    ]
