# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0006_auto_20160701_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='blue_button',
            field=models.TextField(blank=True, help_text='The MyMedicare.gov Blue Button text file is stored here.', null=True, verbose_name='Blue Button Text File'),
        ),
    ]
