# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0006_auto_20171016_1605'),
        ('bluebutton', '0002_auto_20170925_2003'),
    ]

    operations = [
    ]
