# Generated by Django 2.2.22 on 2021-07-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0006_auto_20210528_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCrosswalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fhir_id', models.CharField(db_column='fhir_id', db_index=True, default=None, max_length=80)),
                ('user_id_type', models.CharField(choices=[('H', 'HICN'), ('M', 'MBI')], default='H', max_length=1,
                 verbose_name='Hash ID type last used for FHIR_ID lookup')),
                ('_user_id_hash', models.CharField(db_column='user_id_hash', db_index=True, default=None, max_length=64,
                 verbose_name='HASH of User HICN ID')),
                ('_user_mbi_hash', models.CharField(db_column='user_mbi_hash', db_index=True, default=None, max_length=64,
                 null=True, verbose_name='HASH of User MBI ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('crosswalk', models.ForeignKey(blank=True, db_constraint=False, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='bluebutton.Crosswalk')),
            ],
        ),
    ]
