# Generated by Django 4.2.20 on 2025-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0007_archivedcrosswalk__user_mbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='_fhir_id',
            field=models.CharField(db_column='fhir_id', db_index=True, default=None, max_length=80),
        ),
    ]
