# Generated by Django 4.2.24 on 2025-09-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0007_archivedcrosswalk__user_mbi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='_fhir_id',
            field=models.CharField(null=True, unique=False),
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='_fhir_id_v2',
            field=models.CharField(db_column='fhir_id_v2', db_index=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='_fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='archivedcrosswalk',
            name='_fhir_id',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='archivedcrosswalk',
            name='_fhir_id_v2',
            field=models.CharField(db_column='fhir_id_v2', db_index=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='archivedcrosswalk',
            name='_fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, default=None, max_length=80, null=True, unique=True),
        ),
    ]
