# Generated by Django 4.2.24 on 2025-09-23 13:25

from django.db import migrations

def migrate_fhir_id_to_v2(apps, schema_editor):
    Crosswalk = apps.get_model('bluebutton', 'Crosswalk')
    for crosswalk in Crosswalk.objects.all():
        if crosswalk._fhir_id:
            crosswalk._fhir_id_v2 = crosswalk._fhir_id
            crosswalk.save()

def reverse_migrate_v2_to_fhir_id(apps, schema_editor):
    Crosswalk = apps.get_model('bluebutton', 'Crosswalk')
    for crosswalk in Crosswalk.objects.all():
        if crosswalk._fhir_id_v2:
            crosswalk._fhir_id = crosswalk._fhir_id_v2
            crosswalk.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0008_add_v2_v3_fhir_id'),
    ]

    operations = [
        migrations.RunPython(migrate_fhir_id_to_v2, reverse_migrate_v2_to_fhir_id)
    ]
