# Generated by Django 4.2.20 on 2025-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0008_crosswalk__fhir_id_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedcrosswalk',
            name='_fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, default=None, max_length=80, null=True, unique=True, verbose_name='FHIR ID v3'),
        ),
    ]
