# Generated by Django 4.2.24 on 2025-09-23 13:25

from django.db import migrations, models

# TODO - Migration is Unapplied
# This migration needs to be run after deployment of bluebutton 0008 and when all
# instances are running new code (code associatd with the release of bluebutton 0008)


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0008_add_v2_v3_fhir_id'),
    ]

    operations = [
        migrations.AddConstraint(  # After migrate_fhir_id_to_v2 is run, add constraint that a fhir_id_v2 or v3 must be present
            model_name='crosswalk',
            constraint=models.CheckConstraint(
                check=models.Q(fhir_id_v2__isnull=False) | models.Q(fhir_id_v3__isnull=False),
                name='at_least_one_fhir_id_required'
            ),
        ),
    ]
