# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluebutton', '0008_auto_20160727_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueButtonText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_content', models.TextField(blank=True, help_text='The MyMedicare.gov Blue Button text file is stored here.', null=True, verbose_name='Blue Button Text File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='crosswalk',
            name='bb_text',
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='beneid',
            field=models.CharField(blank=True, max_length=11, verbose_name='Beneficiary Id'),
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='hicn',
            field=models.CharField(blank=True, max_length=11, verbose_name='Member Number(HICN)'),
        ),
    ]
