# Generated by Django 4.2.20 on 2025-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0009_archivedcrosswalk__fhir_id_v3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcrosswalk',
            name='_fhir_id_v3',
        ),
        migrations.AddField(
            model_name='archivedcrosswalk',
            name='_version',
            field=models.CharField(db_column='version', db_index=True, default=2, max_length=3, null=True, verbose_name='Version of API being used'),
        ),
    ]
