# Generated by Django 4.2.24 on 2025-09-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0009_migrate_fhir_id_to_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosswalk',
            name='_fhir_id',
        ),
        migrations.RemoveField(
            model_name='archivedcrosswalk',
            name='_fhir_id',
        ),
    ]
