# Generated by Django 4.2.26 on 2025-12-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0009_migrate_fhir_id_to_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcrosswalk',
            name='_fhir_id',
        ),
        migrations.RemoveField(
            model_name='crosswalk',
            name='_fhir_id',
        ),
    ]
