# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0009_auto_20160915_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetypecontrol',
            name='group_allow',
        ),
        migrations.RemoveField(
            model_name='resourcetypecontrol',
            name='group_exclude',
        ),
    ]
