# Generated by Django 6.0.2 on 2026-03-31 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0010_remove_archivedcrosswalk__fhir_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='_user_id_hash',
            field=models.CharField(db_column='user_id_hash', db_index=True, default=None, unique=False, max_length=64, null=True, verbose_name='HASH of User HICN ID'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='_user_mbi_hash',
            field=models.CharField(db_column='user_mbi_hash', db_index=True, default=None, unique=False, max_length=64, null=True, verbose_name='HASH of User MBI ID'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id_v2',
            field=models.CharField(db_column='fhir_id_v2', db_index=True, unique=False, max_length=80, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, unique=False, max_length=80, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
