# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0011_auto_20160917_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirserver',
            name='cert_file',
            field=models.TextField(blank=True, help_text='Name of Client Certificate file', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fhirserver',
            name='client_auth',
            field=models.BooleanField(default=False, help_text='Is Client Authentication Required?'),
        ),
        migrations.AddField(
            model_name='fhirserver',
            name='key_file',
            field=models.TextField(blank=True, help_text='Name of Client Key file', max_length=250, null=True),
        ),
    ]
