# Generated by Django 6.0.2 on 2026-04-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0011_alter_crosswalk__user_id_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcrosswalk',
            name='fhir_id_v2',
            field=models.CharField(db_column='fhir_id_v2', db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='archivedcrosswalk',
            name='fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id_v2',
            field=models.CharField(db_column='fhir_id_v2', db_index=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id_v3',
            field=models.CharField(db_column='fhir_id_v3', db_index=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
