# Generated by Django 6.0.6 on 2026-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0011_alter_crosswalk__user_id_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedcrosswalk',
            name='_user_id_hash',
            field=models.CharField(db_column='user_id_hash', db_index=True, default=None, max_length=64, null=True, verbose_name='HASH of User HICN ID'),
        ),
    ]
