# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0012_auto_20170228_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirserver',
            name='server_verify',
            field=models.BooleanField(default=False, help_text='Server Verify (Default=False)'),
        ),
    ]
