# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0013_fhirserver_server_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='user_id_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Hash of User ID'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='beneid',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Beneficiary Id'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='mb_user',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
