# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0013_fhirserver_server_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='hicn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Member Number(HICN)'),
        ),
    ]
