# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-30 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0014_auto_20170630_0406'),
        ('bluebutton', '0014_auto_20170602_1310'),
    ]

    operations = [
    ]
