# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluebutton', '0015_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosswalk',
            name='hicn',
        ),
    ]
