# Generated by Django 2.2.22 on 2021-05-13 19:18

from django.conf import settings
from django.db import migrations, models
from apps.authorization.models import update_grants


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.authorization.migrations.0003_auto_20181203_1843

def migrate_grants(*args, **kwargs):
    update_grants()

class Migration(migrations.Migration):

    replaces = [('authorization', '0001_initial'), ('authorization', '0002_auto_20181203_1542'), ('authorization', '0003_auto_20181203_1843'), ('authorization', '0004_auto_20181218_1447'), ('authorization', '0005_auto_20190227_1737')]

    initial = True

    dependencies = [
        ('dot_ext', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dot_ext', '0001_squashed_0025_auto_20210513_1812'),
        ('oauth2_provider', '0006_auto_20171214_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('beneficiary', 'application')},
            },
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary', 'application'], name='authorizati_benefic_ed2194_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_1d71fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_d92033_idx'),
        ),
        migrations.RunPython(
            code=migrate_grants),
        migrations.CreateModel(
            name='ArchivedDataAccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_27dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_2616e8_idx'),
        ),
        migrations.AlterField(
            model_name='archiveddataaccessgrant',
            name='application',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='archiveddataaccessgrant',
            name='beneficiary',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
