# Generated by Django 3.2.15 on 2022-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_squashed_0005_auto_20190227_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddataaccessgrant',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='dataaccessgrant',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
    ]
