# Generated by Django 2.1.2 on 2018-12-03 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataaccessgrant',
            unique_together={('beneficiary', 'application')},
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary', 'application'], name='authorizati_benefic_ed2194_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_1d71fe_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_d92033_idx'),
        ),
    ]
