# Generated by Django 2.2.24 on 2021-09-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_squashed_0005_auto_20190227_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessgrant',
            name='grant_expiration_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
