# Generated by Django 2.1.2 on 2018-12-03 18:43

from django.db import migrations
from apps.authorization.models import update_grants


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20181203_1542'),
    ]

    operations = [
        migrations.RunPython(update_grants)
    ]
