# Generated by Django 2.1.2 on 2018-12-03 18:43

from django.db import migrations
from django.conf import settings
from oauth2_provider.settings import oauth2_settings
from apps.authorization.models import update_grants


def migrate_grants(*args, **kwargs):
    try:
        update_grants()
    except Exception:
        pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authorization', '0002_auto_20181203_1542'),
    ]

    operations = [
        migrations.RunPython(migrate_grants)
    ]
