# Generated by Django 6.0.2 on 2026-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20230513_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessgrant',
            name='include_samhsa',
            field=models.BooleanField(default=False),
        ),
    ]
