# Generated by Django 4.2.20 on 2025-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20230513_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddataaccessgrant',
            name='version',
            field=models.CharField(db_column='version', help_text='API version (e.g., v2, v3, or other future values)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dataaccessgrant',
            name='version',
            field=models.CharField(db_column='version', help_text='API version (e.g., v2, v3, or other future values)', max_length=5, null=True),
        ),
    ]
