# Generated by Django 2.1.2 on 2018-12-18 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0003_auto_20181203_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDataAccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['beneficiary'], name='authorizati_benefic_27dc5d_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveddataaccessgrant',
            index=models.Index(fields=['application'], name='authorizati_applica_2616e8_idx'),
        ),
    ]
