# Generated by Django 4.2.20 on 2025-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_archiveddataaccessgrant_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddataaccessgrant',
            name='version',
            field=models.CharField(db_column='version', default=2, help_text='API version (e.g., 2, 3, or other future values)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccessgrant',
            name='version',
            field=models.CharField(db_column='version', default=2, help_text='API version (e.g., 2, 3, or other future values)', max_length=3),
        ),
    ]
