apiVersion: v1
kind: Pod
spec:
  containers:
    - name: bb2-cbc-build
      image: docker:20-dind
      tty: true
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  nodeSelector:
      Agents: true
