name: Generate JSON from BFD FSH Files

on:
  schedule:
    # Run on day 1 and day 15 of the month at 8:00 AM UTC
    - cron: '0 8 1,15 * *'
  workflow_dispatch:
  push:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:

    # Checkout BFD Repo (public repo)
    - name: Checkout BFD Repo
      uses: actions/checkout@v4
      with:
        repository: CMSgov/beneficiary-fhir-data
        path: beneficiary-fhir-data
        fetch-depth: 0

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Verify Node/npm was installed
    - name: Verify Node Installation
      run:  |
        node --version
        npm --version

    # Install Sushi
    - name: Install Sushi
      run:  |
        npm install -g fsh-sushi fhirpath
        sushi --version

    # Generate JSON from FSH
    - name: Generate JSON
      run: |
        ls -la
        cd beneficiary-fhir-data/apps/bfd-model-idr/sushi
        sushi build

    # Confirm JSON Output
    - name: Verify generated JSON
      run: |
        echo "Checking output directory"
        ls beneficiary-fhir-data/apps/bfd-model-idr/sushi/fsh-generated/resources

    # Checkout BB Static Site Repo Repo (public repo)
    - name: Checkout BB Static Site Repo
      uses: actions/checkout@v4
      with:
        repository: CMSgov/bluebutton-site-static
        path: bluebutton-site-static
        fetch-depth: 0

    - name: Create and checkout branch
      run: |
        cd bluebutton-site-static
        git checkout -b json-update-$(date +%Y-%m-%d)
        git status

    - name: Copy + rename JSON files
      run:  |
        cd beneficiary-fhir-data/apps/bfd-model-idr/sushi/fsh-generated/resources
        ls -la
        for file in CodeSystem-*.json; do
          [ -e "$file" ] || continue
          filename=$(basename "$file")
          new_filename="${filename#CodeSystem-}"
          echo "Copying $file to bluebutton-site-static/src/content/fhir/CodeSystem/$new_filename"
          cp "$file" "bluebutton-site-static/src/content/fhir/CodeSystem/$new_filename"
        done

    - name: Check for changes
      id: check-for-changes
      run: |
        cd bluebutton-site-static
        git add .
        git status
        if git diff --cached --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected, skipping commit and push"
        else
          echo "Changes detected, committing and pushing"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and Push Changes
      if: steps.check-for-changes.outputs.changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        cd bluebutton-site-static
        git commit -m "Update JSON from BFD FSH files - $(date +%Y-%m-%d)"
        git push origin json-update-$(date +%Y-%m-%d)

    - name: Create Pull Request
      if: steps.check-for-changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update JSON from BFD FSH files - $(date +%Y-%m-%d)"
        title: "Update JSON from BFD FSH files - $(date +%Y-%m-%d)"
        body: "This PR updates the JSON files generated from the BFD FSH files. Please review and merge if everything looks good."
        base: master