name: Generate JSON from BFD FSH Files

on:
  schedule:
    # Run on day 1 and day 15 of the month at 8:00 AM UTC
    - cron: '0 8 1,15 * *'
  workflow_dispatch:
  push:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:

    # Checkout BFD Repo (public repo)
    - name: Checkout BFD Repo
      uses: actions/checkout@v4
      with:
        repository: CMSgov/beneficiary-fhir-data
        path: beneficiary-fhir-data

    - name: Verify BFD Repo Checkout
      run:  |
        ls
        ls beneficiary-fhir-data

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Verify Node/npm was installed
    - name: Verify Node Installation
      run:  |
        node --version
        npm --version

    # Install Sushi
    - name: Install Sushi
      run: npm install -g fsh-sushi fhirpath

    # Verify sushi was installed
    - name: Verify Sushi Install
      run: sushi --version

    # Generate JSON from FSH
    - name: Generate JSON
      run: |
        cd beneficiary-fhir-data/apps/bfd-model-idr/sushi
        sushi build

    # Confirm JSON Output
    - name: Verify generated JSON
      run: |
        echo "Checking output directory"
        ls beneficiary-fhir-data/apps/bfd-model-idr/sushi/fsh-generated/resources