name: tofu-plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to plan'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - sandbox
          - prod
      service:
        description: 'Service to plan (or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - 00-bootstrap
          - 01-config
          - 10-cluster
          - 20-microservices
  pull_request:
    paths:
      - 'ops/services/**'
      - 'ops/modules/**'

concurrency:
  group: tofu-plan-or-apply-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan ${{ github.event.inputs.environment || 'test' }}
    runs-on: codebuild-bb-${{ (github.event.inputs.environment || 'test') == 'test' && 'test' || 'prod' }}-web-server-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenTofu & AWS
        uses: ./.github/actions/setup-tofu
        with:
          environment: ${{ github.event.inputs.environment || 'test' }}
          non-prod-account: ${{ secrets.NON_PROD_ACCOUNT }}
          prod-account: ${{ secrets.PROD_ACCOUNT }}

      - name: Tofu Plan
        run: scripts/tofu-run
        env:
          ENV: ${{ github.event.inputs.environment || 'test' }}
          SERVICE: ${{ github.event.inputs.service || 'all' }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
