name: tofu-fmt

on:
  pull_request:
    paths:
      - 'ops/services/**'
      - 'ops/modules/**'
      - '.github/workflows/tofu-fmt.yml'

jobs:
  fmt:
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenTofu
        uses: ./.github/actions/install-tofu

      - name: tofu fmt
        run: tofu fmt -check -diff -recursive .
